### ISSUE TITLE
Throws EISDIR error on startup

### ISSUE THREAD

**Issue by manvel-khnkoyan** [DoubleSymmetry/react-native-track-player#1138]
Whenever I import a library,

`import TrackPlayer from 'react-native-track-player';`

this throws an error

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:612:3)
    at Object.readSync (../app/node_modules/graceful-fs/polyfills.js:147:28)
    at tryReadSync (node:fs:382:20)
    at Object.readFileSync (node:fs:419:19)
    at UnableToResolveError.buildCodeFrameMessage (../app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:304:17)
    at new UnableToResolveError (../app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:290:35)
    at ModuleResolver.resolveDependency (../app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (../app/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at ../app/node_modules/metro/src/lib/transformHelpers.js:271:42
    at ../app/node_modules/metro/src/Server.js:1097:37

OS: Mac Os
I did everything according to the instructions

Here are my package.json dependencies
  ```
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.14.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/netinfo": "^6.0.0",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "axios": "^0.21.1",
    "buffer": "^6.0.3",
    "fast-xml-parser": "^3.18.0",
    "mobx": "^6.1.8",
    "mobx-react-lite": "^3.2.0",
    "path": "^0.12.7",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-fs": "^2.16.6",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-reanimated": "^2.0.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.18.1",
    "react-native-swift": "^1.2.3",
    "react-native-track-player": "^1.2.6"
  }
```

**Comment by mazr422** [comment]
same error
