### ISSUE TITLE
[IOS] Pod install error after run `react-native swiftify`

### ISSUE THREAD

**Issue by GabrielGomesBarbosa** [DoubleSymmetry/react-native-track-player#1171]
Hi folks, i need help with this library, i get error when i run `pod install` on `ios` folder.

**Environment:**
OS: MAC OS Catalina 10.15.7
Ruby: ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin19]
CocoaPod: 1.10.1
XCode: 12.4
Node: 12.20.0
NPM: 6.14.8
React Native: 0.64.1
React Native Track Player: 1.2.7
React Native Swift: 1.2.3
IOS Emulator: IPhone 12 with IOS 14.4
  
**To Reproduce:**
1. Create a new react native project `npx react-native init <project-name>`.
2. Install track player `npm install --save react-native-track-player`.
3. Install react-native-swift `npm install --save react-native-swift`.
4. Run swiftify `npx react-native swiftify`.
5. Run link `npx react-native link`
6. `cd ios`
7. `pod install`
8. See the error

**Additional:**
When i ran `npx react-native swiftify` the file `RNPlaceholder.swift` is created, and when i ran `npx react-native link react-native-track-player` instead `npx react-native link` the `Podfile` is modified like image bellow.

![image](https://user-images.githubusercontent.com/37483241/120080119-cb613800-c08d-11eb-8570-bf7050058d70.png)

But...i still get the same error when i run `pod install` on `ios` folder.

**Error:**
```
Analyzing dependencies
Downloading dependencies
Installing react-native-track-player (1.2.7)
Generating Pods project
[!] An error occurred while processing the post-install hook of the Podfile.

[Xcodeproj] Consistency issue: no parent for object `RNPlaceholder.swift`: `SourcesBuildPhase`, `SourcesBuildPhase`

/usr/local/lib/ruby/gems/2.7.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project/object/helpers/groupable_helper.rb:19:in `parent'
/usr/local/lib/ruby/gems/2.7.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project/object/build_file.rb:71:in `ascii_plist_annotation'
/usr/local/lib/ruby/gems/2.7.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:296:in `block in to_ascii_plist'
/usr/local/lib/ruby/gems/2.7.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:295:in `each'
/usr/local/lib/ruby/gems/2.7.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:295:in `to_ascii_plist'
/usr/local/lib/ruby/gems/2.7.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:364:in `block in save'
/usr/local/lib/ruby/gems/2.7.0/gems/atomos-0.1.3/lib/atomos.rb:21:in `block in atomic_write'
/usr/local/Cellar/ruby@2.7/2.7.3/lib/ruby/2.7.0/tempfile.rb:291:in `open'
/usr/local/lib/ruby/gems/2.7.0/gems/atomos-0.1.3/lib/atomos.rb:17:in `atomic_write'
/usr/local/lib/ruby/gems/2.7.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:363:in `save'
/Users/gabrielgomes/Documents/project-lessons/react-native/audiotest/node_modules/react-native/scripts/react_native_pods.rb:136:in `block in exclude_architectures'
/Users/gabrielgomes/Documents/project-lessons/react-native/audiotest/node_modules/react-native/scripts/react_native_pods.rb:127:in `each'
/Users/gabrielgomes/Documents/project-lessons/react-native/audiotest/node_modules/react-native/scripts/react_native_pods.rb:127:in `exclude_architectures'
/Users/gabrielgomes/Documents/project-lessons/react-native/audiotest/node_modules/react-native/scripts/react_native_pods.rb:161:in `react_native_post_install'
/Users/gabrielgomes/Documents/project-lessons/react-native/audiotest/ios/Podfile:27:in `block (3 levels) in from_ruby'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/podfile.rb:179:in `post_install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:897:in `run_podfile_post_install_hook'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:885:in `block in run_podfile_post_install_hooks'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:145:in `message'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:884:in `run_podfile_post_install_hooks'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:329:in `block (2 levels) in create_and_save_projects'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/xcode/pods_project_generator/pods_project_writer.rb:61:in `write!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:328:in `block in create_and_save_projects'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:307:in `create_and_save_projects'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:178:in `integrate'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:166:in `install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Files:**

package.json

```
{
  "name": "audiotest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.1",
    "react-native": "0.64.1",
    "react-native-swift": "^1.2.3",
    "react-native-track-player": "^1.2.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "isSwift": true
}
```

Podfile

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'audiotest' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'audiotestTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
```

**UPDATE:**
If i ran the `pod install` before step 4 `npx react-native swiftify` the app compiles and open on emulator, but if i run `pod install` after `npx react-native swiftify` i get the error.

**Comment by dcvz** [comment]
Instead of using `react-native-swiftify` what happens if you do this instead: https://github.com/DoubleSymmetry/react-native-track-player/blob/main/docs/Installation.md#ios-enable-swift-library-not-found-for--lswiftcoreaudio-for-architecture-x86_64

does it work?

**Comment by GabrielGomesBarbosa** [comment]
Thanks for your answer... i will reproduce the steps, and change the step 3 to follow this: https://github.com/DoubleSymmetry/react-native-track-player/blob/main/docs/Installation.md#ios-enable-swift-library-not-found-for--lswiftcoreaudio-for-architecture-x86_64

I will back soon with answer.

**Comment by GabrielGomesBarbosa** [comment]
@dcvz Thanks... now it's working fine.

I think that the documentation need be more clear, i follow the documentation steps, maybe put the step of XCode before installation library of `react-native-swift`... just my suggestion.

Thanks a lot.
