### ISSUE TITLE
Android background execution

### ISSUE THREAD

**Issue by osioalberto** [doublesymmetry/react-native-track-player#1313]
**Describe the bug**
It seems that the player cannot be controlled when the app is in background. If the audio stops, it is not possible to start it again on a different track without unlocking the phone. Any attempt to play some tracks results in app crash with the following exception

```
Caught exception
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=it.dotdotdot.etruscoguide/com.guichaguri.trackplayer.service.MusicService }: app is in background uid UidRecord{4bbb480 u0a412 TRNB bg:+3d0h44m29s297ms idle change:idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1795)
	at android.app.ContextImpl.startService(ContextImpl.java:1740)
	at android.content.ContextWrapper.startService(ContextWrapper.java:738)
	at android.content.ContextWrapper.startService(ContextWrapper.java:738)
	at com.guichaguri.trackplayer.module.MusicModule.waitForConnection(MusicModule.java:108)
	at com.guichaguri.trackplayer.module.MusicModule.getQueue(MusicModule.java:410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:246)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:923)
```

**To Reproduce**
- start to play some audio while app is foregrounded
- lock the screen
- await for the track to end (no other tracks should be in the queue now)
- the try to start another track by sending a websocket message

**Environment (please complete the following information):**
React native info
```
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 620.71 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.7.0 - /var/folders/w2/jn6rky295sz7tpkd4bwj5wb00000gn/T/yarn--1635253136485-0.3704272740792369/node
    Yarn: 1.22.17 - /var/folders/w2/jn6rky295sz7tpkd4bwj5wb00000gn/T/yarn--1635253136485-0.3704272740792369/yarn
    npm: 7.6.3 - ~/.nvm/versions/node/v15.7.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 15.0, DriverKit 20.4, macOS 11.3, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 13.0/13A233 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
    Python: 2.7.16 - /Users/alberto/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.4 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

react-native-track-player version: 2.1.1
Testing on real device

**Comment by bradleyflood** [comment]
Thanks @osioalberto Are you able to investigate and/or create a fix PR?

**Comment by jspizziri** [comment]
Given the lack of feedback here and the Android rewrite I'm going to close this ticket. Please test on v2.2.0-rc3 or higher and I'll reopen if its still an issue.

**Comment by RamProg** [comment]
I'm currently having this issue on production with 3.2.0 nightly.

```
Fatal Exception: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.charmander.pikachu/com.doublesymmetry.trackplayer.service.MusicService }: app is in background uid UidRecord{46d20f0 u0a331 TPSL idle procs:0 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1941)
       at android.app.ContextImpl.startService(ContextImpl.java:1887)
       at android.content.ContextWrapper.startService(ContextWrapper.java:793)
       at android.content.ContextWrapper.startService(ContextWrapper.java:793)
       at com.doublesymmetry.trackplayer.module.MusicModule.setupPlayer(MusicModule.java:184)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:920)
```
