### ISSUE TITLE
Crash due to conflict with react-native-video 

### ISSUE THREAD

**Issue by alois-beto** [doublesymmetry/react-native-track-player#1314]
If the application crash on Android when executing
```typescript
await TrackPlayer.setupPlayer();
```
with this error:
```
java.lang.NoSuchMethodError: No virtual method setAudioAttributes(Lcom/google/android/exoplayer2/audio/AudioAttributes;)V in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' appears in /data/app/com.***-2/base.apk)
	at com.guichaguri.trackplayer.service.MusicManager.createLocalPlayback(MusicManager.java:135)
	at com.guichaguri.trackplayer.service.MusicBinder.setupPlayer(MusicBinder.java:42)
	at com.guichaguri.trackplayer.module.MusicModule.lambda$setupPlayer$0$MusicModule(MusicModule.java:165)
	at com.guichaguri.trackplayer.module.-$$Lambda$MusicModule$fjHQ08dDKyrfXst5x4CJP27Uoh8.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

This is caused by a conflict of native dependency `exoplayer` with `react-native-video >= 5.2.0` only if `exoplayer` is manually linked like this (`android/settings.gradle`):

```
include ':react-native-video'
project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')
```

**Solution: Do not manually link exoplayer when installing `react-native-video`**

I am closing this issue because there is no bug related to `react-native-track-player`. I just want that if it ever happens to someone else, they won't have trouble finding out where it came from (unlike me) 😉

**Comment by Fairbrook** [comment]
So... for anyone who needs the exo-player functionality with react-native-video and react-native-track-player. Wich means you need this code in react-native.config.js
``` 
'react-native-video': {
      platforms: {
        android: {
          sourceDir: '../node_modules/react-native-video/android-exoplayer'
        }
      }
    }
```
Is more than probable that your app is going to crash due to the difference in version between both libraries, to solve it you need to make one of them use the exo-player version of the other
I struggle a lot with this so i made a react-native-track-player patch (for patch-package) that hopefully someone will find useful
[patch](https://gist.github.com/Fairbrook/53127f8a05c020836a64f6c19b71f889)
**IMPORTANT: since I don't need the metadata of any quickplayer file, I completely deleted that part while upgrading**
