### ISSUE TITLE
App is crashing when capabilities added in TrackPlayer.updateOptions.  Version: 2.2.0-beta10

### ISSUE THREAD

**Issue by rajpootathar** [DoubleSymmetry/react-native-track-player#1346]
**Describe the bug**
When capabilities added in track player app crashed

**To Reproduce**
- Add capabilities using function **TrackPlayer.updateOptions**  crashed the app

**Environment**
"react-native-track-player": "2.2.0-beta10",
"react-native": "0.64.2",

**Code**
```js
   TrackPlayer.updateOptions({
      stopWithApp: true,
      alwaysPauseOnInterruption: true,
      capabilities: [
        TrackPlayer.CAPABILITY_PLAY,
        TrackPlayer.CAPABILITY_PAUSE,
        TrackPlayer.CAPABILITY_STOP,
        TrackPlayer.CAPABILITY_SKIP_TO_NEXT,
        TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS,
      ],
    })

```

**Error**
Android Studio Logcat 

```
 java.lang.NullPointerException: it must not be null
        at com.doublesymmetry.trackplayer.service.MusicService.updateOptions$lambda-12(MusicService.kt:82)
        at com.doublesymmetry.trackplayer.service.MusicService.lambda$Ih_RN-KpJ6B95ZcoMDpvFHFfr9E(Unknown Source:0)
        at com.doublesymmetry.trackplayer.service.-$$Lambda$MusicService$Ih_RN-KpJ6B95ZcoMDpvFHFfr9E.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:264)
        at android.app.ActivityThread.main(ActivityThread.java:7581)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```
**MusicService.kt:82**
![image](https://user-images.githubusercontent.com/7583598/145405648-3e951398-0219-4b14-8c1d-f21813f0aa94.png)

**Platform**
Android

**Comment by rajpootathar** [comment]
```js
import { Capability } from 'react-native-track-player'

// Capability needs to be used from `Capability` instead of TrackPlayer like

capabilities: [
    Capability.Play,
    Capability.Pause,
    Capability.JumpForward,
    Capability.JumpBackward,
    Capability.Stop
  ]
