### ISSUE TITLE
Crash on Android P, when I configure windowLayoutInDisplayCutoutMode to shortEdges

### ISSUE THREAD

**Issue by ekoooo** [doublesymmetry/react-native-track-player#1347]
**Describe the bug**

Add `<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>` config to `styles.xml`, app crash on start.

Crash Reporter:
```text
FATAL EXCEPTION: main

java.lang.ExceptionInInitializerError

FATAL EXCEPTION: main
Process: com.example, PID: 31071
java.lang.ExceptionInInitializerError
	at androidx.core.view.WindowInsetsCompat.toWindowInsetsCompat(WindowInsetsCompat.java:113)
	at androidx.core.view.ViewCompat$1.onApplyWindowInsets(ViewCompat.java:2473)
	at android.view.View.dispatchApplyWindowInsets(View.java:9799)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7076)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7080)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7080)
	at android.view.ViewGroup.dispatchApplyWindowInsets(ViewGroup.java:7080)
	at android.view.ViewRootImpl.dispatchApplyInsets(ViewRootImpl.java:1632)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1734)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1443)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7125)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:935)
	at android.view.Choreographer.doCallbacks(Choreographer.java:747)
	at android.view.Choreographer.doFrame(Choreographer.java:682)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:921)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6649)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
Caused by: java.lang.NullPointerException
	at androidx.core.util.Preconditions.checkNotNull(Preconditions.java:64)
	at androidx.core.view.WindowInsetsCompat.toWindowInsetsCompat(WindowInsetsCompat.java:113)
	at androidx.core.view.WindowInsetsCompat$BuilderImpl20.build(WindowInsetsCompat.java:1058)
	at androidx.core.view.WindowInsetsCompat$Builder.build(WindowInsetsCompat.java:996)
	at androidx.core.view.WindowInsetsCompat.<clinit>(WindowInsetsCompat.java:56)
	... 22 more

```

**To Reproduce**
1. `git clone https://github.com/DoubleSymmetry/react-native-track-player.git`
2. `cd react-native-track-player`
3. `yarn`
4. `cd example`
5. `yarn`
6.  open `react-native-track-player/example/android/app/src/main/res/values/styles.xml` and add `<item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>` config to style
7. `yarn android`

**Environment (please complete the following information):**
```text
info Fetching system and libraries information...
System:
    OS: macOS 11.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 73.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.8.0/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.2, 26.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-P | Google Play Intel x86 Atom
      Android NDK: 21.1.6352462
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

What `react-native-track-player` version are you using?
```
react-native-track-player@2.1.2
```

![image](https://user-images.githubusercontent.com/8793618/145543568-ec9a07aa-888f-4ef1-88b6-81aeab68d71d.png)

**Code**
`react-native-track-player/example/android/app/src/main/res/values/styles.xml`

```xml
<resources>

    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="android:textColor">#000000</item>
        <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
    </style>

</resources>
```

**Comment by jspizziri** [comment]
@ekoooo , can you confirm if this is still an issue in `v2.2.0-rc3`?

**Comment by ekoooo** [comment]
> v2.2.0-rc3

hi @jspizziri, i tested `v2.2.0-rc3` version in the example project and this issue is still exists.

**Comment by jspizziri** [comment]
@mpivchev flagging this for you in the event you think it should be addressed in 2.2.0. If it should come in a subsequent release let me know.

**Comment by mpivchev** [comment]
Adding this as low priority, since it's not directly related to the player, but more so UI rendering.

**Comment by mpivchev** [comment]
This seems like an issue with Android UI itself and nothing related to this library.
