### ISSUE TITLE
Android crash when I launch TrackPlayer

### ISSUE THREAD

**Issue by manuelTaiwa** [DoubleSymmetry/react-native-track-player#1403]
**Describe the Bug**
Android crash when I launch TrackPlayer

**Steps To Reproduce**

**Code To Reproduce**

        ```
const currentTrack = await TrackPlayer.getCurrentTrack()
        if (session.intro) {

            setTimeCode(session.intro)
        }

        if (currentTrack !== null) {
            if (audioSession.id === session.id) {
                return;
            }

        }

        await TrackPlayer.destroy()

        const setupPlayer = await TrackPlayer.setupPlayer()

        const updateOptions = await TrackPlayer.updateOptions({
            // Media controls capabilities
            capabilities: [
                Capability.Play,
                Capability.Pause,

            ],
            stopWithApp: true,

            // Capabilities that will show up when the notification is in the compact form on Android
            compactCapabilities: [Capability.Play, Capability.Pause,],

            // Icons for the notification on Android (if you don't like the default ones)


        });
        // Add a track to the queue

        setAudioSession(session)
        const addSession = await TrackPlayer.add({
            id: session.id,
            url: session.audio,
            title: session.title,
            artist: session.expert,
            artwork: session.image
        });

        // Start playing it
        setAudioState("playing")



        await TrackPlayer.play()
```

**Environment Info:**
Android :
   buildToolsVersion = "30.0.0"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
**How I can Help**
 ```
java.lang.NoSuchMethodError: No virtual method setAudioAttributes(Lcom/google/android/exoplayer2/audio/AudioAttributes;)V in class Lcom/google/android/exoplayer2/SimpleExoPlayer; or its super classes (declaration of 'com.google.android.exoplayer2.SimpleExoPlayer' appears in /data/app/~~f4RCPnknhSDVaSXSXE3MSg==/com.taiwa.manuel.atempo-cJ4k6STdUv8Iy4zXxSSdow==/base.apk)
        at com.guichaguri.trackplayer.service.MusicManager.createLocalPlayback(MusicManager.java:135)
        at com.guichaguri.trackplayer.service.MusicBinder.getPlayback(MusicBinder.java:34)
        at com.guichaguri.trackplayer.module.MusicModule.lambda$getCurrentTrack$24$MusicModule(MusicModule.java:424)
        at com.guichaguri.trackplayer.module.-$$Lambda$MusicModule$Xm2tTFhYcHlc8y6vDfMFWxLovSE.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1139)
```

What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by manuelTaiwa** [comment]
I found the problem, it was because of the react-native-purchasely library. I don't know why this library crashed the track player.

**Comment by robyweb** [comment]
@manuelTaiwa did you figure out how/why react-native-purchasely was crashing the track player? We are experiencing the same issue, but we don't have react-native-purchasely in our project.

**Comment by manuelTaiwa** [comment]
Hello @robyweb,
I haven't found why. But maybe for you too it's a library that comes into conflict with the track-player.
I have read that some people have particular problems when they use react-native-video and react-native-track-player

**Comment by red-made** [comment]
I have the same problem, happened after upgrading expo to sdk 45, someone know how to solve it?
