### ISSUE TITLE
ForegroundServiceStartNotAllowedException on Android 12 when starting ForegroundService

### ISSUE THREAD

**Issue by marf** [doublesymmetry/react-native-track-player#1551]
**Describe the Bug**

Hello, we are seeing several crashes on Android 12 devices of this type:

`Unable to create service com.guichaguri.trackplayer.service.MusicService: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.myapp/com.guichaguri.trackplayer.service.MusicService`

Reading some articles online it seems Android 12 changed the way it handles foreground services:

https://stackoverflow.com/questions/70044393/fatal-android-12-exception-startforegroundservice-not-allowed-due-to-mallows

They suggest using workers but I do not thing it is a feasible solution for music player apps using notifications to handle the music playback in background.

Stacktrace:

```
Caused by android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.esound/com.guichaguri.trackplayer.service.MusicService
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
       at android.os.Parcel.readParcelable(Parcel.java:3345)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2432)
       at android.os.Parcel.createException(Parcel.java:2421)
       at android.os.Parcel.readException(Parcel.java:2404)
       at android.os.Parcel.readException(Parcel.java:2346)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:8040)
       at android.app.Service.startForeground(Service.java:733)
       at com.guichaguri.trackplayer.service.MusicService.onCreate(MusicService.java:134)
```

Any ideas on how we should solve this?

Thanks!

**Comment by jspizziri** [comment]
Please search old issues before filing a new bug (this is one that's been reported multiple times).

The short version is that android 12 & SDK 31 are supported in 2.2.0-rc3 and we will not be backporting a fix to lower versions (anything at or before 2.1).

https://github.com/doublesymmetry/react-native-track-player/issues/1193

**Comment by marf** [comment]
@jspizziri I have already seen that issue but the crash reported was different from the one I reported here.
If they are related to the same issue I didn't know.

**Comment by MaxJadav** [comment]
@marf  Do you have any solution?

**Comment by marf** [comment]
Unfortunately not :(

**Comment by RamProg** [comment]
I'm having the exact same problem.

**Comment by ys-sherzad** [comment]
We're experiencing this issue too with the latest version:

```
Exception android.app.ForegroundServiceStartNotAllowedException:
  at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel (ForegroundServiceStartNotAllowedException.java:54)
  at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel (ForegroundServiceStartNotAllowedException.java:50)
  at android.os.Parcel.readParcelableInternal (Parcel.java:4787)
  at android.os.Parcel.readParcelable (Parcel.java:4755)
  at android.os.Parcel.createExceptionOrNull (Parcel.java:3018)
  at android.os.Parcel.createException (Parcel.java:3007)
  at android.os.Parcel.readException (Parcel.java:2990)
  at android.os.Parcel.readException (Parcel.java:2932)
  at android.app.IActivityManager$Stub$Proxy.setServiceForeground (IActivityManager.java:6978)
  at android.app.Service.startForeground (Service.java:743)
  at com.guichaguri.trackplayer.service.metadata.MetadataManager.updateNotification (MetadataManager.java:324)
  at com.guichaguri.trackplayer.service.metadata.MetadataManager.setActive (MetadataManager.java:312)
  at com.guichaguri.trackplayer.service.MusicManager.onPause (MusicManager.java:182)
  at com.guichaguri.trackplayer.service.player.ExoPlayback.onPlayerStateChanged (ExoPlayback.java:320)
  at com.guichaguri.trackplayer.service.player.LocalPlayback.onPlayerStateChanged (LocalPlayback.java:204)
  at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$5$com-google-android-exoplayer2-ExoPlayerImpl$PlaybackInfoUpdate (ExoPlayerImpl.java:828)
  at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate$$ExternalSyntheticLambda5.invokeListener
  at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke (BasePlayer.java:182)
  at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll (ExoPlayerImpl.java:845)
  at com.google.android.exoplayer2.ExoPlayerImpl.access$000 (ExoPlayerImpl.java:43)
  at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run (ExoPlayerImpl.java:826)
  at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners (ExoPlayerImpl.java:736)
  at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo (ExoPlayerImpl.java:710)
  at com.google.android.exoplayer2.ExoPlayerImpl.prepare (ExoPlayerImpl.java:242)
  at com.google.android.exoplayer2.SimpleExoPlayer.prepare (SimpleExoPlayer.java:1196)
  at com.guichaguri.trackplayer.service.player.LocalPlayback.resetQueue (LocalPlayback.java:150)
  at com.guichaguri.trackplayer.service.player.LocalPlayback.reset (LocalPlayback.java:183)
  at com.guichaguri.trackplayer.module.MusicModule.lambda$reset$11$com-guichaguri-trackplayer-module-MusicModule (MusicModule.java:323)
  at com.guichaguri.trackplayer.module.MusicModule$$ExternalSyntheticLambda14.run
  at android.os.Handler.handleCallback (Handler.java:942)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8757)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
```
I'm wondering if we need to ask for permission and whether adding the following in `AndroidManifest` could resolve this issue:
```
<uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
```

**Info**
"react-native": "0.70.6",
"react-native-track-player": "^3.2.0",

**Comment by sonorus-eric** [comment]
> ve-track-player": "^3.2.0",

me too
