### ISSUE TITLE
reset() causes IllegalStateException

### ISSUE THREAD

**Issue by DennisdeWitNL** [doublesymmetry/react-native-track-player#1647]
**Describe the Bug**
Since the latest 3.0 release, we cannot use TrackPlayer.reset() correctly anymore. It causes an IllegalStateException, which I caught with Logcat in the Android Studio. When firing the .reset() function, it doesn't reset the queue, as opposed to previous versions. TrackPlayer.stop(); doesn't remove the current track from the queue either. So now my tracks are stuck in the queue.
 
**Steps To Reproduce**
- Do TrackPlayer.setup();
- Add a track with TrackPlayer.add();
- Play it with TrackPlayer.play();
- Try to reset it with TrackPlayer.reset();

**Code To Reproduce**

```
  const togglePlayback = async (playbackState: State) => {
    const currentTrack = await TrackPlayer.getCurrentTrack();
    if (currentTrack == null) {
      getStreamInfoAndTriggerInitTrackPlayer();
    } else {
      if (playbackState !== State.Playing) {
        await TrackPlayer.play();
      } else {
        await TrackPlayer.reset();
        await getStreamInfoAndTriggerInitTrackPlayer();
      }
    }

```
**Environment Info:**
Paste the results of `npx react-native info`

```
info Fetching system and libraries information...
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 290.52 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/Documents/Apps/node_modules/.bin/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.0, iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0/14A5270f - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.3.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.3 => 0.69.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Paste the exact `react-native-track-player` version you are using**
react-native-track-player@3.0.0

**Real device? Or simulator?**
Fails within the simulator AND real deviced

**What OS are you running?**
Android 11 and higher

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

^^^
None to these, I am by no means a programmer with Java or Swift.

**Caught Log:**
```
2022-08-12 18:08:35.822 17707-17707/com.megahit W/MessageQueue: Handler (android.os.Handler) {3d245ac} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {3d245ac} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
        at android.os.Handler.enqueueMessage(Handler.java:778)
        at android.os.Handler.sendMessageAtTime(Handler.java:727)
        at android.os.Handler.sendMessageDelayed(Handler.java:697)
        at android.os.Handler.sendMessage(Handler.java:635)
        at android.os.Message.sendToTarget(Message.java:468)
        at com.google.android.exoplayer2.util.SystemHandlerWrapper$SystemMessage.sendToTarget(SystemHandlerWrapper.java:153)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.addMediaSources(ExoPlayerImplInternal.java:370)
        at com.google.android.exoplayer2.ExoPlayerImpl.addMediaSources(ExoPlayerImpl.java:628)
        at com.google.android.exoplayer2.ExoPlayerImpl.addMediaSources(ExoPlayerImpl.java:612)
        at com.doublesymmetry.kotlinaudio.players.QueuedAudioPlayer.add(QueuedAudioPlayer.kt:93)
        at com.doublesymmetry.trackplayer.service.MusicService.add(MusicService.kt:203)
        at com.doublesymmetry.trackplayer.module.MusicModule$add$2.invokeSuspend(MusicModule.kt:238)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2022-08-12 18:08:35.823 17707-17707/com.megahit W/MessageQueue: Handler (android.os.Handler) {3d245ac} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {3d245ac} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
        at android.os.Handler.enqueueMessage(Handler.java:778)
        at android.os.Handler.sendMessageAtTime(Handler.java:727)
        at android.os.Handler.sendMessageDelayed(Handler.java:697)
        at android.os.Handler.sendMessage(Handler.java:635)
        at android.os.Message.sendToTarget(Message.java:468)
        at com.google.android.exoplayer2.util.SystemHandlerWrapper$SystemMessage.sendToTarget(SystemHandlerWrapper.java:153)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.prepare(ExoPlayerImplInternal.java:304)
        at com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:507)
        at com.doublesymmetry.kotlinaudio.players.QueuedAudioPlayer.add(QueuedAudioPlayer.kt:95)
        at com.doublesymmetry.trackplayer.service.MusicService.add(MusicService.kt:203)
        at com.doublesymmetry.trackplayer.module.MusicModule$add$2.invokeSuspend(MusicModule.kt:238)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2022-08-12 18:08:35.824 17707-17707/com.megahit W/MessageQueue: Handler (android.os.Handler) {3d245ac} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {3d245ac} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
        at android.os.Handler.enqueueMessage(Handler.java:778)
        at android.os.Handler.sendMessageAtTime(Handler.java:727)
        at android.os.Handler.sendMessageDelayed(Handler.java:697)
        at android.os.Handler.sendMessage(Handler.java:635)
        at android.os.Message.sendToTarget(Message.java:468)
        at com.google.android.exoplayer2.util.SystemHandlerWrapper$SystemMessage.sendToTarget(SystemHandlerWrapper.java:153)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.addMediaSources(ExoPlayerImplInternal.java:370)
        at com.google.android.exoplayer2.ExoPlayerImpl.addMediaSources(ExoPlayerImpl.java:628)
        at com.google.android.exoplayer2.ExoPlayerImpl.addMediaSources(ExoPlayerImpl.java:612)
        at com.doublesymmetry.kotlinaudio.players.QueuedAudioPlayer.add(QueuedAudioPlayer.kt:93)
        at com.doublesymmetry.trackplayer.service.MusicService.add(MusicService.kt:203)
        at com.doublesymmetry.trackplayer.module.MusicModule$add$2.invokeSuspend(MusicModule.kt:238)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2022-08-12 18:08:36.525 17707-17754/com.megahit D/EGL_emulation: app_time_stats: avg=33.47ms min=1.54ms max=438.84ms count=26
2022-08-12 18:08:36.624 17707-17707/com.megahit W/MessageQueue: Handler (android.os.Handler) {3d245ac} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {3d245ac} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:560)
        at android.os.Handler.enqueueMessage(Handler.java:778)
        at android.os.Handler.sendMessageAtTime(Handler.java:727)
        at android.os.Handler.sendMessageDelayed(Handler.java:697)
        at android.os.Handler.sendMessage(Handler.java:635)
        at android.os.Message.sendToTarget(Message.java:468)
        at com.google.android.exoplayer2.util.SystemHandlerWrapper$SystemMessage.sendToTarget(SystemHandlerWrapper.java:153)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.setPlayWhenReady(ExoPlayerImplInternal.java:311)
        at com.google.android.exoplayer2.ExoPlayerImpl.updatePlayWhenReady(ExoPlayerImpl.java:2550)
        at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:733)
        at com.google.android.exoplayer2.BasePlayer.play(BasePlayer.java:104)
        at com.doublesymmetry.kotlinaudio.players.BaseAudioPlayer.play(BaseAudioPlayer.kt:161)
        at com.doublesymmetry.trackplayer.service.MusicService.play(MusicService.kt:224)
        at com.doublesymmetry.trackplayer.module.MusicModule$play$1.invokeSuspend(MusicModule.kt:384)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2022-08-12 18:08:41.052 17707-17850/com.megahit D/BufferPoolAccessor2.0: bufferpool2 0xb400006ee9c14268 : 0(0 size) total buffers - 0(0 size) used buffers - 2017/2042 (recycle/alloc) - 53/2037 (fetch/transfer)
2022-08-12 18:08:41.052 17707-17850/com.megahit D/BufferPoolAccessor2.0: evictor expired: 1, evicted: 1
```

**Comment by jspizziri** [comment]
@DennisdeWitNL Did you use the RCs and it wasn't happening there?

**Comment by jspizziri** [comment]
Cc @mpivchev

**Comment by DennisdeWitNL** [comment]
@jspizziri You are exactly right. Without changing anything to my code, 2.2.0-rc4 worked just fine. If I upgrade to 3.0.0, the reset button crashes the whole module. I need to hard stop the app and restart it. Otherwise there will be no sound. 

I downgraded to 2.2.0-rc4 again, and it works just fine.

**Comment by jspizziri** [comment]
Fascinating. sorry we broke that. We merged in that massive android fix and must've missed this in testing. The good news is it should be a simple fix we can get in early next week.

**Comment by CDBridger** [comment]
this is your culprit [here](https://github.com/doublesymmetry/react-native-track-player/blob/v3.0/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt#L235)

**Comment by jspizziri** [comment]
If that's the case then this pr will fix it:

https://github.com/doublesymmetry/react-native-track-player/pull/1646/files

**Comment by DennisdeWitNL** [comment]
@jspizziri @mpivchev It seems that the PR fails on iOS. The latest Xcode-beta for iOS 16 shows the following error:

```node_modules/react-native-track-player/ios/RNTrackPlayer/RNTrackPlayer.swift:471:16: error build: 'reset' is inaccessible due to 'internal' protection level
```

I have literally copied all the files in the PR, so I wouldn't miss anything.

Thank you,
Dennis

**Comment by mpivchev** [comment]
@DennisdeWitNL this is fixed and merged.
