### ISSUE TITLE
Service.startForeground() not allowed due to mAllowStartForeground false

### ISSUE THREAD

**Issue by RamProg** [doublesymmetry/react-native-track-player#1666]
**Describe the Bug**
Production crashes. 99% on Android 12. 100% with the app in the background.

```
Fatal Exception: java.lang.RuntimeException: Unable to create service com.guichaguri.trackplayer.service.MusicService: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.economist.darwin/com.guichaguri.trackplayer.service.MusicService
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4567)
       at android.app.ActivityThread.access$1700(ActivityThread.java:256)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
```
Caused by android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.economist.darwin/com.guichaguri.trackplayer.service.MusicService
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
       at android.os.Parcel.readParcelable(Parcel.java:3334)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2421)
       at android.os.Parcel.createException(Parcel.java:2410)
       at android.os.Parcel.readException(Parcel.java:2393)
       at android.os.Parcel.readException(Parcel.java:2335)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7158)
       at android.app.Service.startForeground(Service.java:736)
       at com.guichaguri.trackplayer.service.MusicService.onCreate(MusicService.java:125)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4554)
       at android.app.ActivityThread.access$1700(ActivityThread.java:256)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Steps To Reproduce**
I haven't been able to reproduce it, but It has happened in production many times.

**Code To Reproduce**

```
    private void onStartForeground() {
        try {
            boolean serviceForeground = false;

            if(manager != null) {
                // The session is only active when the service is on foreground
                serviceForeground = manager.getMetadata().getSession().isActive();
            }

            if(!serviceForeground) {
                ReactInstanceManager reactInstanceManager = getReactNativeHost().getReactInstanceManager();
                ReactContext reactContext = reactInstanceManager.getCurrentReactContext();

                // Checks whether there is a React activity
                if(reactContext == null || !reactContext.hasCurrentActivity()) {
                    String channel = Utils.getNotificationChannel((Context) this);

                    // Sets the service to foreground with an empty notification
                    startForeground(1, new NotificationCompat.Builder(this, channel).build());
                    // Stops the service right after
                    stopSelf();
                }
            }
        } catch(Exception ex) {
            // This method shouldn't be throwing unhandled errors even if something goes wrong.
            Log.e(Utils.LOG, "An error occurred while starting foreground", ex);
        }
    }
```

**Environment Info:**
```
System:
    OS: macOS 12.2.1
    CPU: (10) x64 Apple M1 Max
    Memory: 25.82 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.4 => 0.67.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

`"react-native-track-player": "2.1.2"`

I have patched the package to support SDK 31. The reason was that version 2.2.0 was an RC, so not ready for production. I noticed now there's a 3.1.0, but I tried updating and nothing worked, so I'm guessing it's not retro compatible. Also, I saw many issues related to it, so I decided to wait for a more stable version. 

**How I can Help**
I found a bunch of information about it, but now many people saying this can be fixed.

https://stackoverflow.com/questions/70044393/fatal-android-12-exception-startforegroundservice-not-allowed-due-to-mallows
https://developer.android.com/guide/components/foreground-services#java
https://issuetracker.google.com/issues/229000935

**Comment by jspizziri** [comment]
3.1 is considered stable. Please upgrade and report the issues you're having there or read the issues on 2.1 and add manual patches.

**Comment by rborn** [comment]
@jspizziri I keep having this with the 3.1.0 version.  (crashlytics reports)

Android 12 and 13


```
Fatal Exception: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.letsemjoy.app/com.doublesymmetry.trackplayer.service.MusicService
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
       at android.os.Parcel.readParcelable(Parcel.java:3345)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2432)
       at android.os.Parcel.createException(Parcel.java:2421)
       at android.os.Parcel.readException(Parcel.java:2404)
       at android.os.Parcel.readException(Parcel.java:2346)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:8094)
       at android.app.Service.startForeground(Service.java:733)
       at com.doublesymmetry.trackplayer.service.MusicService$observeEvents$4$1.emit(MusicService.kt:374)
       at com.doublesymmetry.trackplayer.service.MusicService$observeEvents$4$1.emit(MusicService.kt:371)
       at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
       at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(:15)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by jspizziri** [comment]
@rborn can you reproduce this issue based on a fork of the repo in the `example` project?

**Comment by jspizziri** [comment]
@rborn understood. As I'm sure you're aware, it's very hard to fix issues that we can't reproduce. The best we could do without repro is speculate on why it might be happening and make some changes. Which, as you might guess, will be hard for us to justify unless this issue reaches a large critical mass.

**Comment by rborn** [comment]
Yes it might be the case, I call setupPlayer when the app starts but won't add anything to the playlist until the user needs to.

**Comment by jspizziri** [comment]
@kyunkakata can you add the stacktrace of the exception? Thanks for finding a repro, I'll investigate soon.

**Comment by kyunkakata** [comment]
My stacktrace as same as rborn's stacktrace.

**Comment by justintoth** [comment]
Same issue here...

```
android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.marriage365.app/com.guichaguri.trackplayer.service.MusicService
    at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
    at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
    at android.os.Parcel.readParcelable(Parcel.java:3334)
    at android.os.Parcel.createExceptionOrNull(Parcel.java:2421)
    at android.os.Parcel.createException(Parcel.java:2410)
    at android.os.Parcel.readException(Parcel.java:2393)
    at android.os.Parcel.readException(Parcel.java:2335)
    at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7158)
    at android.app.Service.startForeground(Service.java:736)
    at com.guichaguri.trackplayer.service.MusicService.onCreate(MusicService.java:3)
    at android.app.ActivityThread.handleCreateService(ActivityThread.java:4554)
    at android.app.ActivityThread.access$1700(ActivityThread.java:256)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
java.lang.RuntimeException: Unable to create service com.guichaguri.trackplayer.service.MusicService: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.marriage365.app/com.guichaguri.trackplayer.service.MusicService
    at android.app.ActivityThread.handleCreateService(ActivityThread.java:4567)
    at android.app.ActivityThread.access$1700(ActivityThread.java:256)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7870)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by guiadissy** [comment]
Any updates on this? It's been happening a lot in my app in production

**Comment by kyunkakata** [comment]
A friendly ping @jspizziri ?

**Comment by jspizziri** [comment]
@kyunkakata @guiadissy no updates. I'm happy to review any PRs you send my way though!

**Comment by ildfreelancer** [comment]
I got same issue, currently I don't know how to fix this, tried to delay 5s but it doesn't work

```
Fatal Exception: android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2f3efcc u0 com.teampenguin.quitapp/com.doublesymmetry.trackplayer.service.MusicService}
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2147)
       at android.app.ActivityThread.access$2800(ActivityThread.java:310)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2376)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

```
Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{7695923 u0 com.teampenguin.quitapp/com.doublesymmetry.trackplayer.service.MusicService}
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2258)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8633)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
  ```

**Comment by RamProg** [comment]
We still have this issue with 3.2.0

**Comment by martinmidtsund** [comment]
@jspizziri Sadly no, it does not seem to resolve this issue with mAllowStartForeground false.

**Comment by smn-snkl** [comment]
We also still have the issue. Since upgrading to nightly, we see thousands of times and it now almost causes 95% of our Android crashes. Interestingly, we only see them for Android 12+.

So I was wondering whether this might be because of this: https://developer.android.com/about/versions/12/behavior-changes-12#foreground-service-launch-restrictions

And also found this StackOverflow article: https://stackoverflow.com/a/75338150

So I'm wondering whether RNTP also needs to use a WorkManager when the [MusicService Intent is created](https://github.com/doublesymmetry/react-native-track-player/blob/e125045106ad3db125a09dc60dab2acc3334f01c/android/src/main/java/com/doublesymmetry/trackplayer/module/MusicModule.kt#L230)?

**Comment by kyunkakata** [comment]
We had the same issues and crashes due to react-native-track-player.
Most of them are startForeground when the app is in the background state (ForegroundService should not start in Background State). And the second is crash due to crash Context.startForegroundService() did not then call Service.startForeground() within 5s. 
We had fixed them and our production app doesn't receive any of them anymore.
I will send a PR soon.

**Comment by praisedavid787** [comment]
> We had the same issues and crashes due to react-native-track-player. Most of them are calling startForeground when the app is in the background state (ForegroundService should not start in Background State). And the second is crash due to crash Context.startForegroundService() did not then call Service.startForeground() within 5s. We had fixed them and our production app doesn't receive any of them anymore. I will send a PR soon.

Hi @kyunkakata do you have any fixes for this yet? Still getting this frequently.

**Comment by puckey** [comment]
Seeing as these crashes only seem to be happening with Samsung phones, I have ordered one to start testing with.

@kyunkakata I am guessing one of the solutions is to reject the setupPlayer call if the app is in the background?

**Comment by puckey** [comment]
@kyunkakata looks great! I took a moment to refactor the code a little: https://github.com/doublesymmetry/react-native-track-player/pull/1974

Perhaps we should reject the `MusicModule#setupPlayer()` promise if we are not foregrounded?

**Comment by kyunkakata** [comment]
@puckey Thank you for those awesome pull request. Hope it will be merged soon.

**Comment by puckey** [comment]
I reworked the [pull request](https://github.com/doublesymmetry/react-native-track-player/pull/1974) to when `MusicModule#setupPlayer` is called when the app is in the background, delay execution until it comes back to the foreground. For those who would like to test, see the pr here: https://github.com/doublesymmetry/react-native-track-player/pull/1974

(We might want to consider emitting some kind of event for this occasion. This would allow developers to send a notification for the user to return to the app in order for the setup to complete.)

**Comment by puckey** [comment]
a fix for this has landed in rc03: https://github.com/doublesymmetry/react-native-track-player/releases/tag/v4.0.0-rc03

`TrackPlayer.setupPlayer(options)` now rejects when it was called in the background on Android. In the background app we are retrying automatically when the app comes back to the foreground in this case, but you could also choose to throw up a retry button or something else: https://github.com/doublesymmetry/react-native-track-player/blob/main/example/src/services/SetupService.ts#L17-L22

**Comment by mitchdowney** [comment]
@puckey this issue appears to still be happening in rc04. Maybe it should be reopened? It seems like @martinmidtsund has discovered something in the Pocket Casts repo that may explain why RNTP has these foreground handling issues: https://github.com/doublesymmetry/react-native-track-player/pull/1974#issuecomment-1492485315

**Comment by mitchdowney** [comment]
This is our most frequent crash on Android using v4.0.0-rc04. 

@puckey when `setupPlayer` rejects while the app is in the background, does that error get thrown in our business logic as well? Should I be wrapping our `setupPlayer` calls in a try/catch? Do I need to keep retrying, or does this `while` take care of that for you?

In Podverse we call this function immediately on app startup: 

```ts
/*
  Delay a second on Android to try to avoid
  not allowed to start service Intent error
  https://github.com/doublesymmetry/react-native-track-player/issues/1812

*/
const timeout = Platform.OS === 'android' ? 1000 : 0
setTimeout(() => {
  PVAudioPlayer.setupPlayer({
    waitForBuffer: true,
    maxCacheSize: 1000000, // 1 GB from KB, this affects Android only I think.
    iosCategoryMode: IOSCategoryMode.SpokenAudio
  }).then(() => {
    audioUpdateTrackPlayerCapabilities()
  })
  
  PVAudioPlayer.setRepeatMode(RepeatMode.Off)
}, timeout)
```

I'm wondering if I can safely remove the setTimeout.

Also, while I see in our logs that we have many crashes within 20 seconds of startup, I also see the same error message for many 3 hours+. I wonder if these are two different situations.

**Comment by jspizziri** [comment]
@mitchdowney have you looked at this recently? https://github.com/doublesymmetry/react-native-track-player/blob/main/example/src/services/SetupService.ts

**Comment by mitchdowney** [comment]
@jspizziri doh...I didn't realize I was looking at example app code, not library code. I will give this `while` / `setup` a try in our business logic.

**Comment by RamProg** [comment]
Not sure why this is closed if it's still happening on the last version?

**Comment by jspizziri** [comment]
See the fresh issue here https://github.com/doublesymmetry/react-native-track-player/issues/1986

**Comment by akankshaingle** [comment]
Solution: Disabling Battery Optimization Restriction
To resolve the issue of apps being interrupted when running in the background, I created a native module to request users to disable battery optimization for the app.

1. Create BatteryOptimizationManager & BatteryOptimizationPackage
Location: android/app/src/main/java/com/yourProject/

These classes handle the interaction with the system's battery optimization settings.

BatteryOptimizationManager.java

`package com.example;

import android.content.Intent;
import android.net.Uri;
import android.os.Build;
import android.provider.Settings;
import android.app.Activity;
import android.content.Context;
import android.os.PowerManager;
import android.util.Log;

import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.Promise;

public class BatteryOptimizationManager extends ReactContextBaseJavaModule {

    private static ReactApplicationContext reactContext;
    private static final String TAG = "BatteryOptimizationManager";

    BatteryOptimizationManager(ReactApplicationContext context) {
        super(context);
        reactContext = context;
    }

    @Override
    public String getName() {
        return "BatteryOptimizationManager";
    }

    @ReactMethod
    public void requestIgnoreBatteryOptimizations(Promise promise) {
        Log.d(TAG, "requestIgnoreBatteryOptimizations invoked");

        Activity activity = getCurrentActivity();
        if (activity != null) {
            PowerManager powerManager = (PowerManager) activity.getSystemService(Context.POWER_SERVICE);
            String packageName = activity.getPackageName();

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                boolean isIgnoring = powerManager.isIgnoringBatteryOptimizations(packageName);
                Log.d(TAG, "Battery optimization ignored: " + isIgnoring);

                if (!isIgnoring) {
                    Intent intent = new Intent();
                    intent.setAction(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS);
                    intent.setData(Uri.parse("package:" + packageName));
                    activity.startActivity(intent);
                    Log.d(TAG, "Request to ignore battery optimizations sent");

                    // Resolve the promise after the intent is sent
                    promise.resolve(true); 
                } else {
                    Log.d(TAG, "Battery optimization already ignored");
                    promise.resolve(true); // Resolve even if it's already ignored
                }
            } else {
                Log.d(TAG, "Battery optimization request not necessary for this Android version");
                promise.reject("ERR_UNSUPPORTED_VERSION", "Battery optimization not supported below Android M");
            }
        } else {
            Log.d(TAG, "Current activity is null");
            promise.reject("ERR_ACTIVITY_NULL", "Current activity is null");
        }
    }

    @ReactMethod
    public void checkBatteryOptimizationStatus(Promise promise) {
        Log.d(TAG, "checkBatteryOptimizationStatus invoked");

        Activity activity = getCurrentActivity();
        if (activity != null) {
            PowerManager powerManager = (PowerManager) activity.getSystemService(Context.POWER_SERVICE);
            String packageName = activity.getPackageName();

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                boolean isIgnoring = powerManager.isIgnoringBatteryOptimizations(packageName);
                Log.d(TAG, "Battery optimization ignored: " + isIgnoring);

                promise.resolve(isIgnoring); // Return the optimization status
            } else {
                Log.d(TAG, "Battery optimization request not necessary for this Android version");
                promise.reject("ERR_UNSUPPORTED_VERSION", "Battery optimization not supported below Android M");
            }
        } else {
            Log.d(TAG, "Current activity is null");
            promise.reject("ERR_ACTIVITY_NULL", "Current activity is null");
        }
    }
}`

BatteryOptimizationPackage.java

`package com.example;

import com.facebook.react.ReactPackage;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.NativeModule;
import com.facebook.react.uimanager.ViewManager;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class BatteryOptimizationPackage implements ReactPackage {

    @Override
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
        List<NativeModule> modules = new ArrayList<>();
        modules.add(new BatteryOptimizationManager(reactContext));
        return modules;
    }

    @Override
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
        return Collections.emptyList();
    }
}`

2. Register the Package in MainApplication.java
Add the BatteryOptimizationPackage in the getPackages() method of MainApplication.java like this:

`import com.cerge.BatteryOptimizationPackage;

@Override
protected List<ReactPackage> getPackages() {
    List<ReactPackage> packages = new PackageList(this).getPackages();
    // Add BatteryOptimizationPackage to manually link the native module
    packages.add(new BatteryOptimizationPackage());
    return packages;
}
`

3. Invoke the Native Module in React Native
Here’s how you can invoke the battery optimization module in your React Native code:

`const { BatteryOptimizationManager } = NativeModules;

let isBatteryOptimizationRequestPending = false;

export const requestBatteryOptimizationPermission = () => {
  if (isBatteryOptimizationRequestPending) {
    console.log("Battery optimization request already pending, skipping...");
    return;
  }

  console.log("requestBatteryOptimizationPermission invoked");
  isBatteryOptimizationRequestPending = true;

  if (BatteryOptimizationManager) {
    BatteryOptimizationManager.checkBatteryOptimizationStatus()
      .then((isIgnoring) => {
        if (isIgnoring) {
          console.log("Battery optimization is already disabled.");
          isBatteryOptimizationRequestPending = false;
        } else {
          Alert.alert(
            "Battery Optimization",
            "We need to disable battery optimization to ensure the app can run in the background without interruptions. This is necessary for detecting beacons and updating your location in real-time. Would you like to continue?",
            [
              {
                text: "Cancel",
                style: "cancel",
                onPress: () => {
                  console.log("User canceled the battery optimization request");
                  isBatteryOptimizationRequestPending = false;
                },
              },
              {
                text: "OK",
                onPress: () => {
                  console.log("User confirmed");
                  BatteryOptimizationManager.requestIgnoreBatteryOptimizations()
                    .then(() => {
                      console.log("Battery optimization request completed");
                      isBatteryOptimizationRequestPending = false;
                    })
                    .catch((error) => {
                      console.error("Error requesting battery optimization:", error);
                      isBatteryOptimizationRequestPending = false;
                    });
                },
              },
            ],
            { cancelable: false }
          );
        }
      })
      .catch((error) => {
        console.error("Error checking battery optimization status:", error);
        isBatteryOptimizationRequestPending = false;
      });
  } else {
    console.error("BatteryOptimizationManager is not available");
    isBatteryOptimizationRequestPending = false;
  }
};
`
