### ISSUE TITLE
Invariant Violation: "main" has not been registered on expo

### ISSUE THREAD

**Issue by SOG-web** [doublesymmetry/react-native-track-player#1675]
**Describe the Bug**
I get `Invariant Violation: "main" has not been registered` even after following due process

```
TypeError: null is not an object (evaluating 'TrackPlayer.RATING_HEART')
at C:\Users\Olalekan Raheem\Documents\Github\rou-nx-expo\node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at C:\Users\Olalekan Raheem\Documents\Github\rou-nx-expo\node_modules\react-native\Libraries\Core\ExceptionsManager.js:95:4 in reportException
at C:\Users\Olalekan Raheem\Documents\Github\rou-nx-expo\node_modules\react-native\Libraries\Core\ExceptionsManager.js:141:19 in handleException
at C:\Users\Olalekan Raheem\Documents\Github\rou-nx-expo\node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at C:\Users\Olalekan Raheem\Documents\Github\rou-nx-expo\node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError
at C:\Users\Olalekan Raheem\Documents\Github\rou-nx-expo\node_modules\metro-runtime\src\polyfills\require.js:203:6 in guardedLoadModule
at http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.sermonbank&modulesOnly=false&runModule=true:374678:3 in global code

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.
at C:\Users\Olalekan Raheem\Documents\Github\rou-nx-expo\node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at C:\Users\Olalekan Raheem\Documents\Github\rou-nx-expo\node_modules\react-native\Libraries\Core\ExceptionsManager.js:95:4 in reportException
at C:\Users\Olalekan Raheem\Documents\Github\rou-nx-expo\node_modules\react-native\Libraries\Core\ExceptionsManager.js:141:19 in handleException
at C:\Users\Olalekan Raheem\Documents\Github\rou-nx-expo\node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at C:\Users\Olalekan Raheem\Documents\Github\rou-nx-expo\node_modules\@react-native\polyfills\error-guard.js:49:36 in ErrorUtils.reportFatalError
at C:\Users\Olalekan Raheem\Documents\Github\rou-nx-expo\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:370:8 in __guard
at C:\Users\Olalekan Raheem\Documents\Github\rou-nx-expo\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:113:4 in callFunctionReturnFlushedQueue
```

I have done the expo-dev-client step and it successfully builds

**Steps To Reproduce**
`index.js`
```js
import { registerRootComponent } from 'expo';
import TrackPlayer from 'react-native-track-player';

import App from './src/app/App';

// registerRootComponent calls AppRegistry.registerComponent('main', () => App);
// It also ensures that whether you load the app in Expo Go or in a native build,
// the environment is set up appropriately
registerRootComponent(App);
TrackPlayer.registerPlaybackService(() => require('./service'));
```
`App.tsx`
```js
import TrackPlayer, { Capability } from 'react-native-track-player';

// outside the component
async function setup() {
  await TrackPlayer.setupPlayer({});
  await TrackPlayer.updateOptions({
    stoppingAppPausesPlayback: true,
    capabilities: [
      Capability.Play,
      Capability.Pause,
      Capability.SkipToNext,
      Capability.SkipToPrevious,
      Capability.Stop,
      Capability.SeekTo,
      Capability.Like,
    ],
    compactCapabilities: [
      Capability.Play,
      Capability.Pause,
      Capability.SkipToNext,
      Capability.SkipToPrevious,
      Capability.Stop,
      Capability.SeekTo,
      Capability.Like,
    ],
  });
}

// inside App.tsx component
 useEffect(() => {
    setup();
  }, []);
```

`service.js`
```js
module.exports = async function () {
  // This service needs to be registered for the module to work
  // but it will be used later in the "Receiving Events" section
};
```

**Environment Info:**
Paste the results of `npx react-native info`
```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 523.96 MB / 7.93 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8815526
    Visual Studio: Not Found
  Languages:
    Java: 18.0.2.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.2 => 0.68.2 
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
Paste the exact `react-native-track-player` version you are using ` "react-native-track-player": "^3.1.0",`
Real device? Or simulator? `simulator`
What OS are you running? `windows`

**How I can Help**
What can you do to help resolve this? `I which I could do something am not good at android dev yet`
Have you investigated the underlying JS or Swift/Android code causing this bug? `No`
Can you create a Pull Request with a fix? `if I know the solution I can`

**Comment by jspizziri** [comment]
None of our code contributors use or work with expo. I know there are some docs about it, but we don't officially support it, at least anymore. Please ask for help in the discord support channel.

**Comment by objectiveSee** [comment]
I wish somebody had figured this out. I am stuck on the same issue :)
