### ISSUE TITLE
Android Crash: ForegroundServiceDidNotStartInTimeException

### ISSUE THREAD

**Issue by CDBridger** [doublesymmetry/react-native-track-player#1676]
**Describe the Bug**
android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{334a779 u0 nz.co.nbr/com.doublesymmetry.trackplayer.service.MusicService}

using RNTP 3.0.0

I haven't been able to reproduce this crash in my dev environment, I can just see it happening to users via crashalytics

Looks like its only happening for android 12 / API level 32

**Environment Info:**
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 85.55 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.17.0 - /opt/homebrew/bin/npm
    Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 31, 33
      Build Tools: 30.0.3, 31.0.0, 33.0.0
      System Images: android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: ^0.69.4 => 0.69.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**How I can Help**

it looks like the google docs says startForeground needs to be called within 5 seconds of context.startService
but I can't see where NotificationState.POSTED gets called to trigger the event which calls startForeground.

my three current theories as to why this crash is occurring is
- I know setup player is being called by my app on launch, but a track isn't necessarily being added, does this mean the event wont be fired at all? causing it to crash? The only point against this theory is that I would imagine I would be seeing way more crashes if this was the case.
- The event is being subscribed to AFTER it has already been emitted. This would also cause startForeground to not be called. 
- Slow phones take longer than fives seconds to go from context.startService() to startForeground(). I would think this is unlikely because 5 seconds is a pretty damm long time.

Unsure how to investigate/ make tweaks to investigate any of these. Assumptions I have made is that startForegound is only called in NotificationState.POSTED. If true, questions are:

-  Why can it not be called on setupPlayer()? 
-  If It can't be because it needs a track to be added, why does the service have to be started as a foreground one, can it not be started and then promoted to foreground when a track is added? 
- Do I need to avoid calling setupPlayer until I'm about to add a track? This seems cumbersome to implement and not really how it should be done?

**Comment by jspizziri** [comment]
- Please upgrade to 3.1
- Please create a reproduction in the example project

If you do those two things I'll reopen this issue.

**Comment by Vietvantue** [comment]
@jspizziri 
It happens with our app too:
We are using the RNTP version: "react-native-track-player": "^3.2.0"

```Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3d24c5e u0 com.lucidbeta/com.doublesymmetry.trackplayer.service.MusicService}
```

**Comment by mmmoussa** [comment]
We still see this as well with RNTP 3.2.0 across a wide array of Samsung devices

**Comment by bradleyflood** [comment]
I'm seeing this issue too on Samsung devices `Galaxy S10 (SM-G973F)` OS `12` (API `31`)
```
Context.startForegroundService() did not then call Service.startForeground():
```

**Comment by bradleyflood** [comment]
@puckey Are you seeing this lately in your crash reports? (by the way, I use Bugsnag, do you?)

**Comment by martinmidtsund** [comment]
We are seeing lots of these errors on Android 12 and 13. It seems like its mainly Samsung, e.g. models S10, S20, S21 and S22. I currently have not been able to reproduce this on my own phone in development..

## Error

```
RemoteServiceException$ForegroundServiceDidNotStartInTimeException
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e3105cb u0 com.package/com.doublesymmetry.trackplayer.service.MusicService}

android.app.ActivityThread in generateForegroundServiceDidNotStartInTimeException at line 2242
android.app.ActivityThread in throwRemoteServiceException at line 2213
android.app.ActivityThread in -$$Nest$mthrowRemoteServiceException
android.app.ActivityThread$H in handleMessage at line 2505
android.os.Handler in dispatchMessage at line 106
android.os.Looper in loopOnce at line 226
android.os.Looper in loop at line 313
android.app.ActivityThread in main at line 8741
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 571
com.android.internal.os.ZygoteInit in main at line 1067
```

## StackTrace
Last startServiceCommon() call for this service was made here

```
android.app.ContextImpl in startServiceCommon at line 1988
android.app.ContextImpl in startForegroundService at line 1933
android.content.ContextWrapper in startForegroundService at line 839
1
androidx.core.content.ContextCompat$Api26Impl in startForegroundService at line 931
androidx.core.content.ContextCompat in startForegroundService at line 703
androidx.media.session.MediaButtonReceiver in onReceive at line 115
android.app.ActivityThread in handleReceiver at line 4881
android.app.ActivityThread in -$$Nest$mhandleReceiver
android.app.ActivityThread$H in handleMessage at line 2417
android.os.Handler in dispatchMessage at line 106
android.os.Looper in loopOnce at line 226
android.os.Looper in loop at line 313
android.app.ActivityThread in main at line 8741
java.lang.reflect.Method in invoke
com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 571
com.android.internal.os.ZygoteInit in main at line 1067
```

**Comment by martinmidtsund** [comment]
@puckey @jspizziri @mpivchev Sorry to ping you all, I have unfortunately not been able to reproduce this locally yet, as I'm not sure what is causing this, and I'm kind of stuck. It seems this is related to the MediaButtonReceiver from the [AndroidManifest.xml](https://github.com/doublesymmetry/react-native-track-player/blob/main/android/src/main/AndroidManifest.xml#L17) in RNTP:

```
<!-- A receiver that will receive media buttons. Required on pre-lollipop devices -->
<receiver android:name="androidx.media.session.MediaButtonReceiver" android:exported="true">
    <intent-filter>
        <action android:name="android.intent.action.MEDIA_BUTTON" />
    </intent-filter>
</receiver>
```

As the stacktrace is throwing because in file MediaButtonReceiver.java that's included via KotlinAudio is trying to start the service again:
```
at androidx.media.session.MediaButtonReceiver.onReceive (MediaButtonReceiver.java:115)
```

Where the code on that line is:
```
  ContextCompat.startForegroundService(context, intent);
```
Entire function:
```
    @Override
    public void onReceive(Context context, Intent intent) {
        if (intent == null
                || !Intent.ACTION_MEDIA_BUTTON.equals(intent.getAction())
                || !intent.hasExtra(Intent.EXTRA_KEY_EVENT)) {
            Log.d(TAG, "Ignore unsupported intent: " + intent);
            return;
        }
        ComponentName mediaButtonServiceComponentName =
                getServiceComponentByAction(context, Intent.ACTION_MEDIA_BUTTON);
        if (mediaButtonServiceComponentName != null) {
            intent.setComponent(mediaButtonServiceComponentName);
            ContextCompat.startForegroundService(context, intent); <-- OFFENDING LINE
            return;
        }
        ComponentName mediaBrowserServiceComponentName = getServiceComponentByAction(context,
                MediaBrowserServiceCompat.SERVICE_INTERFACE);
        if (mediaBrowserServiceComponentName != null) {
            PendingResult pendingResult = goAsync();
            Context applicationContext = context.getApplicationContext();
            MediaButtonConnectionCallback connectionCallback =
                    new MediaButtonConnectionCallback(applicationContext, intent, pendingResult);
            MediaBrowserCompat mediaBrowser = new MediaBrowserCompat(applicationContext,
                    mediaBrowserServiceComponentName, connectionCallback, null);
            connectionCallback.setMediaBrowser(mediaBrowser);
            mediaBrowser.connect();
            return;
        }
        throw new IllegalStateException("Could not find any Service that handles "
                + Intent.ACTION_MEDIA_BUTTON + " or implements a media browser service.");
    }
```

All errors are in the background, using RNTP 3.2.0 and multiple Android versions as mentioned earlier (seen it on 11, 12 and 13). It looks like this is some media event being sent that's not being handled as it should.

I will gladly debug this more, but I wanted to check in to see if you have any pointers/ideas/thoughts as to how this might be reproduced given the above information?

If the MediaButtonReceiver truly is required only on pre-lollipop (API level < 21) devices, we could perhaps just remove this receiver, as KotlinAudio has a minSdk of 21 and the RNTP example app has a minSdk of 21. Will try this locally with patch-package and see if anything breaks. Do you know of any reason not to remove it?

**Comment by matthieuMay** [comment]
@martinmidtsund 

The problem is not from react native track players but from exoplayer and androidx.media3. 

There are in facts 2 bugs : one on samusung + android 11 and 12 and on on android 13.
The first has been fixed in androidx.media3 (https://github.com/androidx/media/issues/112) but still some occurences under android 13 (https://github.com/androidx/media/issues/167)

A version bump in Kotlin Audio could be a good idea.

On my side I forced the resolution to latest media lib adding in build.gradle :

configurations.all {
  resolutionStrategy { 
    force 'com.google.android.exoplayer:exoplayer:2.18.2'
  }
}

It seems that it actually works as I do not see anything else than android 13 errors.

**Comment by bradleyflood** [comment]
Thanks for the investigation @martinmidtsund . I'm getting several crash reports of this per day.

@dcvz or @jspizziri Any thoughts or suggestions on what we should do here? Upgrade the exoplayer?

**Comment by jspizziri** [comment]
@bradleyflood It's hard to say. Not being able to repro makes it almost impossible to fix. I do think there's an exoplayer upgrade on the way though.

**Comment by martinmidtsund** [comment]
@matthieuMay Thanks for the input! Have seen that issue, but couldn't find that they replicated the same fix from the media beta (https://github.com/androidx/media/commit/acd9e581c494b18f6347f5abb2cf9fc82344c723) into Exoplayer v2.18.2 (https://github.com/google/ExoPlayer/releases), though they say it should be parity between them. 🤷‍♂️ 

If the new version of ExoPlayer fixes the issues for versions < 13 that's great. We'll try removing the duplicate media-receiver first, then bump the ExoPlayer version, to see what does what. :)

**Comment by SMJ93** [comment]
@matthieuMay have you seen anymore crashes on Android 12 since adding `force 'com.google.android.exoplayer:exoplayer:2.18.2'`?

**Comment by matthieuMay** [comment]
@SMJ93 sadly it came back after 10 days without any errors. I guess it improves a bit the situation but it is not 100%

**Comment by ouabing** [comment]
Also see this error in version 3.2, I only see this crashes on Android 12 devices.
We will try to force upgrade exoplayer.

```

# main(2)

android.app.ForegroundServiceDidNotStartInTimeException

Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{582a614 u0 me.x.x/com.doublesymmetry.trackplayer.service.MusicService}
android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1986)
android.app.ActivityThread.access$2800(ActivityThread.java:274)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2211)
android.os.Handler.dispatchMessage(Handler.java:106)
android.os.Looper.loopOnce(Looper.java:210)
android.os.Looper.loop(Looper.java:299)
android.app.ActivityThread.main(ActivityThread.java:8205)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by aidan2129** [comment]
@jspizziri  Seeing this error reported a lot on google play console any reason why this is closed has a solution been found?

**Comment by jspizziri** [comment]
@aidan2129 this issue seems to be with ExoPlayer (an upstream dependency), and it doesn't sound like it's been fixed there from what I can tell. I had originally closed it because no one was able to create a reliable reproduction in the example app. I'll reopen it, but all it will be is a placeholder to upgrade ExoPlayer once it's fixed.

**Comment by martinmidtsund** [comment]
@jspizziri We have had the following patch running in production for 14 days now, and this and related errors has disappeared. 

```
diff --git a/node_modules/react-native-track-player/android/src/main/AndroidManifest.xml b/node_modules/react-native-track-player/android/src/main/AndroidManifest.xml
index 06e392a..2749e5e 100644
--- a/node_modules/react-native-track-player/android/src/main/AndroidManifest.xml
+++ b/node_modules/react-native-track-player/android/src/main/AndroidManifest.xml
@@ -14,13 +13,6 @@
             </intent-filter>
         </service>

-        <!-- A receiver that will receive media buttons. Required on pre-lollipop devices -->
-        <receiver android:name="androidx.media.session.MediaButtonReceiver" android:exported="true">
-            <intent-filter>
-                <action android:name="android.intent.action.MEDIA_BUTTON" />
-            </intent-filter>
-        </receiver>
-
     </application>

 </manifest>
```

If the MediaButtonReceiver truly is required only on pre-lollipop (API level < 21) devices, we could perhaps just remove this receiver in the library, as KotlinAudio has a minSdk of 21 and the RNTP example app has a minSdk of 21?

**Comment by jspizziri** [comment]
@martinmidtsund interesting, that's good to know. However, I'm concerned that removing that might have unintended side effects. I just quickly glanced at [the documentation](https://developer.android.com/reference/androidx/media/session/MediaButtonReceiver) and it seems that a receiver might be necessary to control wired/wireless headset interactions. Have you tested that in your app?

**Comment by martinmidtsund** [comment]
@jspizziri We are currently seeing [this issue](https://github.com/doublesymmetry/react-native-track-player/issues/1775), so we haven't gotten to testing jump forward or backward, but play, pause and volume functions well from wireless bluetooth headset works. (At least with what I'm testing on)

**Comment by jspizziri** [comment]
@martinmidtsund thanks for the info. If you're able to dive into the details with what that receiver actually does and can say create a PR with documentation on why you're confident it wouldn't cause a side effect, I'd happily look deeper into it.

**Comment by surajSanwal** [comment]
facing the same issue 

Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e58ddc6 u0 com.inspiredmumma/com.doublesymmetry.trackplayer.service.MusicService}
       at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2242)
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2213)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2505)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
       
       
       
 Device Info: 
Brand:samsung
Model:Galaxy S21+ 5G
Orientation: Portrait
Version:Android 13

**Comment by SMJ93** [comment]
@matthieuMay we have seen an increase in crashes since forcing `'com.google.android.exoplayer:exoplayer:2.18.2'` so have reverted this change.

We were able to reduce the amount of crashes by removing unnecessary calls to `TrackPlayer.getPosition` and `TrackPlayer.getDuration`.

I would suggest auditing everywhere you interact with the `TrackPlayer` library and remove unnecessary calls. This reduced the crashes for us, but did not completely eradicate the issue.

Hopefully the upstream dependency exoplayer release a fix soon 🤞

**Comment by elliotdickison** [comment]
We are running the patch from @martinmidtsund in prod on ~6.3k devices and have seen this error completely disappear with no complaints from users. We do not support Android < 21.

**Comment by martinmidtsund** [comment]
@dcvz Yes, I think I can manage it in a couple of days. Have some untested additions to it as well, but can discuss that in a draft PR.

**Comment by jspizziri** [comment]
@dcvz i have some concerns about this approach that I mention here https://github.com/doublesymmetry/react-native-track-player/issues/1676#issuecomment-1377364133

But perhaps it's not a problem? I suppose we can test.

**Comment by martinmidtsund** [comment]
@jspizziri I can set up a PR draft where we can discuss and list test results with the proposed changes?

**Comment by puckey** [comment]
Thanks for fixing this @martinmidtsund!

**Comment by ys-sherzad** [comment]
Hi guys, I'm still getting this error which is happening **Android 13**, basically AndroidX:

```
Exception android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException:
  at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException (ActivityThread.java:2245)
  at android.app.ActivityThread.throwRemoteServiceException (ActivityThread.java:2216)
  at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2508)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8757)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1067)
Caused by android.app.StackTrace: Last startServiceCommon() call for this service was made here
  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1988)
  at android.app.ContextImpl.startForegroundService (ContextImpl.java:1933)
  at android.content.ContextWrapper.startForegroundService (ContextWrapper.java:839)
  at android.content.ContextWrapper.startForegroundService (ContextWrapper.java:839)
  at androidx.core.content.ContextCompat$Api26Impl.startForegroundService (ContextCompat.java:1091)
  at androidx.core.content.ContextCompat.startForegroundService (ContextCompat.java:749)
  at androidx.media.session.MediaButtonReceiver.onReceive (MediaButtonReceiver.java:115)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:4894)
  at android.app.ActivityThread.-$$Nest$mhandleReceiver
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2420)
```

`"react-native-track-player": "^3.2.0",`

**Comment by ahoseinian** [comment]
@martinmidtsund shouldn't we publish a new version here after merging this. at least the [yarn registry](https://cdn.jsdelivr.net/npm/react-native-track-player@3.2.0/android/src/main/AndroidManifest.xml) still is pointing to the old version.

**Comment by andordavoti** [comment]
Does the latest version (3.2.0) include the PR to fix it by @martinmidtsund? I'm having production crashes for Samsung Android 13 devices

**Comment by bkostjens** [comment]
Same question here: Using 3.2.0 and getting crashes on Samsung and Nokia devices.
