### ISSUE TITLE
[Android] java.lang.IllegalStateException on reload app (metro)

### ISSUE THREAD

**Issue by GrimDev** [doublesymmetry/react-native-track-player#1846]
**Describe the Bug**
Hi there !

I get the following exception in logcat that makes the app crashes when I reload it from metro (press r)
```
AndroidRuntime: FATAL EXCEPTION: main
12-09 14:25:53.528 17585 17585 E AndroidRuntime: Process: com.tellingtone, PID: 17585
12-09 14:25:53.528 17585 17585 E AndroidRuntime: java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/com.tellingtone/cache/TrackPlayer
12-09 14:25:53.528 17585 17585 E AndroidRuntime: 	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:249)
12-09 14:25:53.528 17585 17585 E AndroidRuntime: 	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:229)
12-09 14:25:53.528 17585 17585 E AndroidRuntime: 	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:194)
12-09 14:25:53.528 17585 17585 E AndroidRuntime: 	at com.doublesymmetry.kotlinaudio.players.BaseAudioPlayer.<init>(BaseAudioPlayer.kt:153)
12-09 14:25:53.528 17585 17585 E AndroidRuntime: 	at com.doublesymmetry.kotlinaudio.players.QueuedAudioPlayer.<init>(QueuedAudioPlayer.kt:14)
12-09 14:25:53.528 17585 17585 E AndroidRuntime: 	at com.doublesymmetry.trackplayer.service.MusicService.setupPlayer(MusicService.kt:92)
12-09 14:25:53.528 17585 17585 E AndroidRuntime: 	at com.doublesymmetry.trackplayer.module.MusicModule$onServiceConnected$1.invokeSuspend(MusicModule.kt:56)
```

**Steps To Reproduce**
Just setup the player, run your app in dev mode with Metro, then after app is launched, press "r" in Metro console.

**Environment Info:**
Paste the results of `npx react-native info`
```
System:
    OS: macOS 13.0
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 597.33 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: 2022.10.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-24 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: 21.4.7075529
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.70.6 => 0.70.6
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
Paste the exact `react-native-track-player` version you are using : 3.2.0
Real device? Or simulator? : Real device
What OS are you running? Android 11

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug? 
Can you create a Pull Request with a fix?

**Comment by jspizziri** [comment]
closing as duplicate https://github.com/doublesymmetry/react-native-track-player/issues/296#issuecomment-1259598282

Please search the issues before creating a new one.
