### ISSUE TITLE
[Android] Error: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by ernestbies** [doublesymmetry/react-native-track-player#1874]
**Describe the Bug**
This problem has been present in the library for a very long time but is still not fixed and all topics related to it are closed. So I decided to create a new one.

Topics related to this issue: [#473](https://github.com/DoubleSymmetry/react-native-track-player/issues/473), [#524](https://github.com/doublesymmetry/react-native-track-player/issues/524), [#1676](https://github.com/doublesymmetry/react-native-track-player/issues/1676).

The problem is serious, has been present for several years and affects the user experience of users using the **react-native-track-player** library.

**Steps To Reproduce**
Lock the screen when building the app. In addition, the problem occurs after listening to a given track for a long period of time.
The problem also occurs when users use the application (data from Crashlytics, reported by users).

1. Run the application via **react-native run-android** and make a screen lock.
2. An error will occur.

```
Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1fac5c6 u0 com.exampleapp.app/com.doublesymmetry.trackplayer.service.MusicService}
       at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2242)
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2213)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2505)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)```
```

Another way to trigger the problem is to replace **startService()** with **startForegroundService()** in the file **MusicModule.kt**. Wait about 10 seconds and after this change application will crash with the same error.

**Replicable on Example App?**
Yes.

**Environment Info:**
The problem occurs on physical devices and emulators. Versions:
"react-native": "^0.70.6"
"react-native-track-player": "^3.2.0"

**Comment by daniel-plewinski** [comment]
same here - since the problem is reported by so many developers maybe it's time to take action

**Comment by PatrykGodlewski** [comment]
Encountering the same problem, I found that there are limitations on apps in the background. Locking the screen, while building the app makes that app as background, in that case, it cant run invoked before on build services. More about these limitations here https://developer.android.com/about/versions/oreo/background

**Comment by jspizziri** [comment]
> maybe it's time to take action

@daniel-plewinski I encourage you to do exactly that! That's the beauty of open source, you're the master of your own destiny. I'll happily review any PRs that you or any other people on this thread submit.

**Comment by ernestbies** [comment]
@jspizziri 

Hey,

thanks for answer. This problem is related with **startForeground()**. Method **startForegroundService()** is not used in library (and you can't just replace it). In the attached topics, the developers were looking for various solutions, but unfortunately none of them solved the problem.

Related error:

```
Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1fac5c6 u0 com.app.exampleapp/com.doublesymmetry.trackplayer.service.MusicService}
       at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2242)
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2213)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2505)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8741)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by elliotdickison** [comment]
> I think this will be solved by #1888

I can confirm this. Down from 20-30 crashes a day to 0. Thank you!

**Comment by nl-danish** [comment]
is this fixed? This error is getting logged the most in crashanalytics, I was thinking if there's a work around or if the issue has been fixed?

**Comment by ping-warren8** [comment]
@ernestbies https://lnkr.fun/422a268

**Comment by roganantonys** [comment]
i too facing the same ForegroundServiceDidNotStartInTimeException now ,
my RNTP version is ^3.2.0 
what should I want to implement in my code ? 
any suggestion @ernestbies @jspizziri @martinmidtsund @daniel-plewinski
