### ISSUE TITLE
Android build fails due to EXO player when using a older version of Android

### ISSUE THREAD

**Issue by JaveriaZubairRayn** [doublesymmetry/react-native-track-player#1913]
java.lang.NoClassDefFoundError: com.google.android.exoplayer2.ExoPlayer$Builder$$ExternalSyntheticLambda17 
is the error when i use logcat.
The app crashes on launch 
Steps to Reproduce: 
- Create a emulator or a real device with the API 23 marshmallow
- run the app 
- the app fails on launch without any console or error on the debugger

**Code To Reproduce**
Please provide a simple code example that allows others to replicate the bug.
compileOptions {
      sourceCompatibility JavaVersion.VERSION_1_8
       targetCompatibility JavaVersion.VERSION_1_8
   }

**Replicable on Example App?**
import TrackPlayer, { RepeatMode } from 'react-native-track-player';

// Creates the player
const setup = async () => {
  await TrackPlayer.setupPlayer({});

  await TrackPlayer.add({
    url: require('track.mp3'),
    title: 'Track Title',
    artist: 'Track Artist',
    artwork: require('track.png')
  });

  TrackPlayer.setRepeatMode(RepeatMode.Queue);
};

**Environment Info:**
Paste the results of `npx react-native info`
>System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 11.30 GB / 31.77 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.17 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.7 => 0.69.7
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Paste the exact `react-native-track-player` version you are using
react-native-track-player 3.2.0
Real device? Or simulator?
happens on both simulator and real device
What OS are you running?
Android Marshmallow API 23

Logcat error message
   java.lang.NoClassDefFoundError: com.google.android.exoplayer2.ExoPlayer$Builder$$ExternalSyntheticLambda17
        at com.google.android.exoplayer2.ExoPlayer$Builder.<init>(ExoPlayer.java:509)
        at com.doublesymmetry.kotlinaudio.players.BaseAudioPlayer.<init>(BaseAudioPlayer.kt:156)
        at com.doublesymmetry.kotlinaudio.players.QueuedAudioPlayer.<init>(QueuedAudioPlayer.kt:14)
        at com.doublesymmetry.trackplayer.service.MusicService.setupPlayer(MusicService.kt:92)
        at com.doublesymmetry.trackplayer.module.MusicModule$onServiceConnected$1.invokeSuspend(MusicModule.kt:56)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@142f8b, Dispatchers.Main]
2023-02-08 12:44:38.368 1278-1278/? E/EGL_emulation: tid 1278: eglCreateSyncKHR(1881): error 0x3004 (EGL_BAD_ATTRIBUTE)

any help regarding this

**Comment by jspizziri** [comment]
@JaveriaZubairRayn you need to upgrade the minimum version you're targeting in your project. API 23 is from 2015 we try to keep this library in sync with the `react-native` project requirements.
