### ISSUE TITLE
TrackPlayer.reset() crashes on android using rc3

### ISSUE THREAD

**Issue by jeroenptrs** [doublesymmetry/react-native-track-player#1978]
**Describe the Bug**
Using 4.0.0-rc3, performing a .reset() will crash the app.

**Steps To Reproduce**
use .reset()

You get errors similar to:
```
java.lang.NullPointerException: null cannot be cast to non-null type com.doublesymmetry.kotlinaudio.models.AudioItemHolder
                                                                                                        at com.doublesymmetry.kotlinaudio.notification.NotificationManager.getCurrentItemHolder(NotificationManager.kt:159)
                                                                                                        at com.doublesymmetry.kotlinaudio.notification.NotificationManager.setNotificationMetadata(NotificationManager.kt:54)
                                                                                                        at com.doublesymmetry.kotlinaudio.players.BaseAudioPlayer.updateNotificationMetadataIfAutomatic$kotlin_audio_release(BaseAudioPlayer.kt:286
```

**Code To Reproduce**
TrackPlayer.reset()

**Replicable on Example App?**
Can you replicate this bug in the [React Native Track Player Example App](https://github.com/doublesymmetry/react-native-track-player/tree/main/example)? Most likely yes

**Environment Info:**
Paste the results of `npx react-native info`
Paste the exact `react-native-track-player` version you are using
Real device? Or simulator? Real device, Nokia 7+
What OS are you running? Android

**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by mitchdowney** [comment]
I'm also getting this error in 4.0.0-rc03:

```
com.doublesymmetry.kotlinaudio.notification.NotificationManager.getCurrentItemHolder
NotificationManager.kt, line 159
java.lang.NullPointerException: null cannot be cast to non-null type com.doublesymmetry.kotlinaudio.models.AudioItemHolder
```

```
com.doublesymmetry.kotlinaudio.notification.NotificationManager.getCurrentItemHolder NotificationManager.kt:159
com.doublesymmetry.kotlinaudio.notification.NotificationManager.setNotificationMetadata NotificationManager.kt:54
com.doublesymmetry.kotlinaudio.players.BaseAudioPlayer.updateNotificationMetadataIfAutomatic$kotlin_audio_release BaseAudioPlayer.kt:286
com.doublesymmetry.kotlinaudio.players.BaseAudioPlayer$PlayerListener.onMediaItemTransition BaseAudioPlayer.kt:646
com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$14 ExoPlayerImpl.java:1882
com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda27.invoke
com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke ListenerSet.java:281
com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0 ListenerSet.java:190
com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run
com.google.android.exoplayer2.util.ListenerSet.flushEvents ListenerSet.java:211
com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo ExoPlayerImpl.java:1955
com.google.android.exoplayer2.ExoPlayerImpl.removeMediaItems ExoPlayerImpl.java:658
com.google.android.exoplayer2.BasePlayer.clearMediaItems BasePlayer.java:84
com.doublesymmetry.kotlinaudio.players.BaseAudioPlayer.clear BaseAudioPlayer.kt:377
com.doublesymmetry.kotlinaudio.players.QueuedAudioPlayer.clear QueuedAudioPlayer.kt:251
com.doublesymmetry.trackplayer.service.MusicService.onTaskRemoved MusicService.kt:631
android.app.ActivityThread.handleServiceArgs ActivityThread.java:4654
android.app.ActivityThread.-$$Nest$mhandleServiceArgs
android.app.ActivityThread$H.handleMessage ActivityThread.java:2176
android.os.Handler.dispatchMessage Handler.java:106
android.os.Looper.loopOnce Looper.java:201
android.os.Looper.loop Looper.java:288
android.app.ActivityThread.main ActivityThread.java:7884
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:548
com.android.internal.os.ZygoteInit.main ZygoteInit.java:936
```

**Comment by puckey** [comment]
The following KotlinAudio pr should fix this issue: https://github.com/doublesymmetry/KotlinAudio/pull/71

**Comment by ravi-roxiler** [comment]
Can this issue be solved facing on nightly as well

**Comment by puckey** [comment]
@dcvz can we publish another rc?

**Comment by ravi-roxiler** [comment]
@puckey @dcvz yes can we publish this because it causing multiple crashes for Android

**Comment by bahmanworld** [comment]
Same here
First time works, but when i wanna reset player it crashes app.

**Comment by artherrer** [comment]
@bahmanworld same here. Any solution?

**Comment by dodgex** [comment]
@bahmanworld @artherrer try rc4

**Comment by bahmanworld** [comment]
> @bahmanworld @artherrer try rc4

Thank you @dodgex, i already did it and TrackPlayer works fine,
not just `.reset()` but everything works fine. i see no more bugs in RC04.

and, Thank you @dcvz and your awesome team for this great library
