### ISSUE TITLE
Occasional error "{AppName} keeps stopping", on closing an app (with react-native-track-player) active in the background.ground

### ISSUE THREAD

**Issue by Manil-SoftNEP** [doublesymmetry/react-native-track-player#1980]
**Describe the Bug**
I am creating an app which uses react-native-track-player in the background. The app plays a track regardless of wether the app is in the foreground or the background. 
Occasionally on closing the app I get an android message that states '{App Name} keeps stopping'.
![Screenshot_1680678339](https://user-images.githubusercontent.com/106724447/230006078-cec315b1-76e5-49fc-85ce-57093724814a.png)
The app works as intended, with the exception of the sporadic error messages. 

The error feedback on the device provides the following details
```log
Report Type: Crash
Package name: com.myApp

Package version: 1004
Package version name: 1.0.0
Installed by: com.android.vending
Process name: com.myApp
Time: Monday, 3 April 2023
System app: false
System: 
  Device: a02
  Build type: user
  Model: SM-M022G
Product: a02ins
SDK version: 30
Release: 11
Codename: REL
Crash:
  Exception class name: java.lang.NumberFormatException
  Source file: Integer.java
  Source class: java.lang.Integer
  Source method: parseInt
  Line number: 615
  Stack trace: 
    java.lang.numberformatexception: For input string: "null" 
    at java.lang.Integer.parseInt(Integer.java: 615) 
    at java.lang.Integer.parseInt(Integer.java: 650) 
    at com.doublesymmetry.trackplayer.module.MusicModule$q.m(Unknown Source:64)
    at g8.a.e(Unknown Source:11)
    at w8.u0.run(Unknown Source:129)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.Handler.ActivityThread.main(ActivityThread.java:8633)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
    Suppressed: w8.s0: [b2{Cancelling}@183e27f, Dispatchers.Main]
```

**Steps To Reproduce**
You can find the code for this bug [here](https://github.com/Manil-SoftNEP/Transient-Audio-Stream).
Just clone the repo and 
    use the _'./TransientAudioStream.apk'_ file to install the app
    or
    Run the app using 
        `npm i` and 
        `npx react-native run-android`

**Code To Reproduce**
I am registering the TrackPlayer's PlaybackService in the ./index.js.
```js
// ./index.js
import {AppRegistry} from 'react-native';
import TrackPlayer from 'react-native-track-player';

import {PlaybackService} from './service';
import App from './App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
TrackPlayer.registerPlaybackService(() => PlaybackService);
```

And the TrackPlayer's Playback Services are stored in ./service.js
```js
// ./service.js
import TrackPlayer, {Event} from 'react-native-track-player';

export const PlaybackService = async function () {
  TrackPlayer.addEventListener(Event.RemotePlay, () => TrackPlayer.play());
  TrackPlayer.addEventListener(Event.RemotePause, () => TrackPlayer.pause());
};
```

And this is how I am setting up the track player.
```js
// ./App.js
  const track = {
    id: 0,
    url: 'https://streaming.test.net:12345/auto-dj',
    title: 'ShoutCast Stream',
    artist: 'React Native',
    genre: 'ShoutCast Stream',
    artwork: 'https://d33l68.cloudfront.net/5540b349/ecfc9/img/header_logo.svg',
  };

  const setUpTrackPlayer = async track => {
    try {
      await TrackPlayer.setupPlayer();
      await TrackPlayer.updateOptions({
        stopWithApp: true,
        android: {
          appKilledPlaybackBehavior:
            AppKilledPlaybackBehavior.StopPlaybackAndRemoveNotification,
        },
        // Media controls capabilities
        capabilities: [Capability.Play, Capability.Pause],

        // Capabilities that will show up when the notification is in the compact form on Android
        compactCapabilities: [Capability.Play, Capability.Pause],
      });
      await TrackPlayer.add([track]);
      TrackPlayer.play();
    } catch (err) {
      console.error(`Could not setup track player. ${err}`);
      TrackPlayer.remove();
    }
  };

  useEffect(() => {
    setUpTrackPlayer(track);

    return () => {
      TrackPlayer.remove();
    };
  }, []);
```

**Environment Info:**
```log
  System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 116.77 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: Not Found
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: 2022.08.08.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```
I am using `react-native-track-player` version `3.2.0`.
The issue occurs in both the Real device and the Simulator.

How can I stop the error from popping up?

**Comment by puckey** [comment]
Please use 4.0.0-rc04: https://www.npmjs.com/package/react-native-track-player/v/4.0.0-rc04

**Comment by Manil-SoftNEP** [comment]
> Please use 4.0.0-rc04: https://www.npmjs.com/package/react-native-track-player/v/4.0.0-rc04

@puckey Thank you for the answer. It fixed the issue.

**Comment by francowanseele** [comment]
Hello, I am wondering.. why we should install 4.0.0-rc04? If I search for this library, npm give me the command `npm i react-native-track-player`, that install version 3.2.0.

To keep this library working in the future, we should install version 4.0.0 or just install with the command `npm i react-native-track-player`??

I am using this library and I got confused with this. 

Thanks :)
