### ISSUE TITLE
[android][rc-03] Crash: Unable to start service com.doublesymmetry.trackplayer.service.MusicService@78647c9 with null

### ISSUE THREAD

**Issue by ZeroPie** [doublesymmetry/react-native-track-player#1986]
**Describe the Bug**`

Firebase Analytics is reporting the following crash
```
Fatal Exception: java.lang.RuntimeException: Unable to start service com.doublesymmetry.trackplayer.service.MusicService@78647c9 with null: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.dierotenbullen.app/com.doublesymmetry.trackplayer.service.MusicService
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5192)
       at android.app.ActivityThread.access$2200(ActivityThread.java:315)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2324)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
       
```
      
       
```
       Caused by android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.rnapp.app/com.doublesymmetry.trackplayer.service.MusicService
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
       at android.os.Parcel.readParcelable(Parcel.java:3346)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2433)
       at android.os.Parcel.createException(Parcel.java:2422)
       at android.os.Parcel.readException(Parcel.java:2405)
       at android.os.Parcel.readException(Parcel.java:2347)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:8095)
       at android.app.Service.startForeground(Service.java:733)
       at com.doublesymmetry.trackplayer.service.MusicService.startAndStopEmptyNotificationToAvoidANR(MusicService.kt:115)
       at com.doublesymmetry.trackplayer.service.MusicService.onStartCommand(MusicService.kt:92)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5174)
       at android.app.ActivityThread.access$2200(ActivityThread.java:315)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2324)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8751)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
**Steps To Reproduce**
`Alas cannot reproduce, but firebase analytics reports the crashes.`

**Code To Reproduce**
use "react-native-track-player": "^4.0.0-rc03"

**Replicable on Example App?**
Alas not replicable

**Environment Info:**
```System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 95.86 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.volta/tools/image/node/16.13.1/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/16.13.1/bin/npm
    Watchman: 2023.03.13.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-31 | ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.1 => 0.66.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Paste the exact `react-native-track-player` version you are using**
`"react-native-track-player": "^4.0.0-rc03"`


**How I can Help**
What can you do to help resolve this?
Have you investigated the underlying JS or Swift/Android code causing this bug?
Can you create a Pull Request with a fix?

**Comment by s123121** [comment]
That is the known issue from rc03. Please use rc04

**Comment by jspizziri** [comment]
Please upgrade to rc4.

**Comment by mitchdowney** [comment]
@jspizziri we're on 4.0.0-rc04, and I see this crash in AppCenter after 10 seconds:

```
kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend
android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.podverse/com.doublesymmetry.trackplayer.service.MusicService
Device: Galaxy S21 Ultra 5G
Crashed after: 10s
OS: Android 13

---

android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel ForegroundServiceStartNotAllowedException.java:54
android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel ForegroundServiceStartNotAllowedException.java:50
android.os.Parcel.readParcelableInternal Parcel.java:4787
android.os.Parcel.readParcelable Parcel.java:4755
android.os.Parcel.createExceptionOrNull Parcel.java:3018
android.os.Parcel.createException Parcel.java:3007
android.os.Parcel.readException Parcel.java:2990
android.os.Parcel.readException Parcel.java:2932
android.app.IActivityManager$Stub$Proxy.setServiceForeground IActivityManager.java:6978
android.app.Service.startForeground Service.java:743
com.doublesymmetry.trackplayer.service.MusicService$observeEvents$4$1.emit MusicService.kt:510
com.doublesymmetry.trackplayer.service.MusicService$observeEvents$4$1.emit MusicService.kt:507
kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl SharedFlow.kt:383
kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith ContinuationImpl.kt:33
kotlinx.coroutines.DispatchedTask.run DispatchedTask.kt:106
android.os.Handler.handleCallback Handler.java:942
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loopOnce Looper.java:226
android.os.Looper.loop Looper.java:313
android.app.ActivityThread.main ActivityThread.java:8757
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:571
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1067
```

As part of the attempted solution, I added the `while` based call to `setupPlayer`, as I thought it might help prevent this error. Here's our [setup code](https://github.com/podverse/podverse-rn/blob/develop/src/services/playerAudioSetup.ts#L21).

We haven't collected enough data yet to say if there is at least a decrease in the frequency of the crash. We just went live yesterday, and I see this morning this crash was reported once more in the latest version.

This is related to our convo at https://github.com/doublesymmetry/react-native-track-player/issues/1666#issuecomment-1499324857

**Comment by ZeroPie** [comment]
Can confirm, still happening in rc4

**Comment by jspizziri** [comment]
All, additional details that would be helpful on this ticket:

1. The specific Android device models.
2. A reliable path to reproduce.

**Comment by ZeroPie** [comment]
@jspizziri 
    "react-native-track-player": "^4.0.0-rc04",

**Comment by ZeroPie** [comment]
> All, additional details that would be helpful on this ticket:
> 1. The specific Android device models.
> 2. A reliable path to reproduce.

1:
Galaxy S22 Android 13
Galaxy A12 Android 13
Moto G(60)s Android 12
Galaxy S10 Android 12
Galaxy S10e Android 12
Galaxy S22 Android 12
Galaxy S20FE Android13
Pixel 6 Android 13
Galaxy S20 FE Android 13
Redmi 10 5G Android 12
Galaxy A52 Android 13
Galaxy A52s 5G Android 12
Motorola Edge 30 Ultra Android 12
Motorola Edge 30 Ultra Android 12

2. That's the tricky part, we cannot reproduce it on our own devices, it's just some users in the prod firebase crashlytics

**Comment by jspizziri** [comment]
@ZeroPie thanks for the additional information. A couple follow up questions:

1. Have you happened to or do you have the ability to test on any of the devices you listed above? My instinct here is that it's fairly device-specific.
2. Are the users that are experiencing the crashes getting them consistently? Or are they intermittent.

**Comment by ZeroPie** [comment]
> @ZeroPie thanks for the additional information. A couple follow up questions:
> 
> 1. Have you happened to or do you have the ability to test on any of the devices you listed above? My instinct here is that it's fairly device-specific.
> 2. Are the users that are experiencing the crashes getting them consistently? Or are they intermittent.

@jspizziri we have tested some of the devices (especially the popular ones (Samsung S20) and we don't have those.

2. Correct, intermittently, it is consistent that they do experience this during the first second, but they do not experience this every time they open the app.

**Comment by karolChorzepa** [comment]
Note that this error appears only if you do not have the phone connected by cable to the computer, I would recommend debugging the wifi

**Comment by RamProg** [comment]
https://github.com/doublesymmetry/react-native-track-player/issues/1551

This crash is gonna be one year soon, should we throw a party?

**Comment by jspizziri** [comment]
@RamProg maybe submitting a PR would be a better use of your time.

**Comment by Manhha3010** [comment]
add this to File android/app/build.gradle 
   implementation project(':react-native-track-player')
  implementation 'com.github.doublesymmetry:kotlinaudio:v2.0.0-rc6'

**Comment by Manhha3010** [comment]
<img width="466" alt="image" src="https://user-images.githubusercontent.com/29350391/236985896-24c608f5-4c33-49ad-bf36-d50959d9ff80.png">
Still crash on 4.0.0-rc04
Caused by android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.babiuni/com.doublesymmetry.trackplayer.service.MusicService
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
       at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
       at android.os.Parcel.readParcelableInternal(Parcel.java:4787)
       at android.os.Parcel.readParcelable(Parcel.java:4755)
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3018)
       at android.os.Parcel.createException(Parcel.java:3007)
       at android.os.Parcel.readException(Parcel.java:2990)
       at android.os.Parcel.readException(Parcel.java:2932)
       at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6978)
       at android.app.Service.startForeground(Service.java:743)
       at com.doublesymmetry.trackplayer.service.MusicService.startAndStopEmptyNotificationToAvoidANR(MusicService.java:115)
       at com.doublesymmetry.trackplayer.service.MusicService.onStartCommand(MusicService.java:92)
       at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5243)
       at android.app.ActivityThread.-$$Nest$mhandleServiceArgs()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2447)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by fmalbacete** [comment]
Hello Guys!!

I'm having the same issue, anyone already have success trying to reolve this ?

( we are trying in ourside too ) 

Thanks!!!

**Comment by matt-dalton** [comment]
It looks like the Play Store are now sending our notifications implying this could become a blocker - has anyone managed to find a solution?

**Comment by gavrichards** [comment]
Yes we have received this message from Google Play:

> SERVICE UPDATE
> 
> Hi Google Play Developer,
> 
> We have identified a potential issue in your app(s) that may be related to foreground service background start restrictions introduced in Android 12. To maintain proper functionality of your app and avoid user confusion, please take a look at the information below.
> 
> Affected app(s): (redacted)
> 
> On Android 12 (API level 31) and higher, apps can only start [foreground services](https://developer.android.com/guide/components/foreground-services) while they are in the foreground or in one of the [exempted](https://developer.android.com/guide/components/foreground-services#background-start-restriction-exemptions) situations. If an app tries to start a foreground service while it is in the background and does not meet the [exemptions](https://developer.android.com/guide/components/foreground-services#background-start-restriction-exemptions), the system will throw a [ForegroundServiceStartNotAllowedException](https://developer.android.com/reference/android/app/ForegroundServiceStartNotAllowedException). We've received reports that your app is throwing the ForegroundServiceStartNotAllowedException.
> 
> To aid in diagnosing this issue, we recommend checking whether your [app performs background starts](https://developer.android.com/guide/components/foreground-services#background-start-restrictions-check). Some potential solutions could include using alternative APIs such as WorkManager, confirming calls to [startForeground](https://developer.android.com/reference/android/app/Service#startForeground(int,%20android.app.Notification)) are initiated from one of the [allowed states](https://developer.android.com/guide/components/foreground-services#background-start-restriction-exemptions), catching the ForegroundServiceNotALlowedException and/or [updating your app's logic](https://developer.android.com/guide/components/foreground-services#background-start-restriction-update-app-logic).

**Comment by m1heng** [comment]
Any progress on this?
With rc04, we still have this Error 
```
ForegroundServiceStartNotAllowedException
Service.startForeground() not allowed due to mAllowStartForeground false: service com.xxx/com.doublesymmetry.trackplayer.service.MusicService
```
And only on Android 12/13

**Comment by l3k** [comment]
Hello Folks

Sorry for my bad english

I tried to fix this problem, but I don't know if it works for everyone, so I ask you to test it

In version 4.0.0-rc04, replace the event.notificationStateChange.collect function in android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt

event.notificationStateChange.collect {
                when (it) {
                    is NotificationState.POSTED -> {
                        if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.S)
                        {
                            with(androidx.core.app.NotificationManagerCompat.from(applicationContext)) {
                                notify(it.notificationId, it.notification)
                            }
                        }
                        else {
                            startForeground(it.notificationId, it.notification)
                        }
                    }
                    is NotificationState.CANCELLED -> {
                        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                            stopForeground(STOP_FOREGROUND_REMOVE)
                        } else {
                            @Suppress("DEPRECATION")
                            stopForeground(true)
                        }

                        stopSelf()
                    }
                }
            }

**Comment by DineshRajput21** [comment]
@l3k You are a genius man. I confirm it's working fine for me now. I have been facing this issue for a long time ago and finally, it's working now. Thanks, mate!

**Comment by babzcraig** [comment]
> @l3k You are a genius man. I confirm it's working fine for me now. I have been facing this issue for a long time ago and finally, it's working now. Thanks, mate!

@DineshRajput21 how were you able to confirm this fix? Were you able to reproduce the issue consistently enough to determine that this patch fixed it?

**Comment by mitchdowney** [comment]
After 3 days of Beta testing with hundreds of users, we have had 0 of these crashes over that time 🎉 with previous releases we would see crash reports for this within 24 hours. It's still early but so far this fix appears to be working.

**Comment by l3k** [comment]
> > @l3k You are a genius man. I confirm it's working fine for me now. I have been facing this issue for a long time ago and finally, it's working now. Thanks, mate!
> 
> @DineshRajput21 how were you able to confirm this fix? Were you able to reproduce the issue consistently enough to determine that this patch fixed it?

check [this PR](https://github.com/doublesymmetry/react-native-track-player/pull/2048), probably resolved and tested

**Comment by arakovskis** [comment]
Still happens in 4.0.0-rc06

Phone: Pixel 6
Android: 13

1. Receive notification
2. Open the app from notification
3. Close the app

```java
FATAL EXCEPTION: main
Process: com.mindtalesapp, PID: 8021
java.lang.RuntimeException: Unable to start service com.doublesymmetry.trackplayer.service.MusicService@31f23e with null: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.mindtalesapp/com.doublesymmetry.trackplayer.service.MusicService
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4673)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2179)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.mindtalesapp/com.doublesymmetry.trackplayer.service.MusicService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4816)
	at android.os.Parcel.readParcelable(Parcel.java:4778)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3006)
	at android.os.Parcel.createException(Parcel.java:2995)
	at android.os.Parcel.readException(Parcel.java:2978)
	at android.os.Parcel.readException(Parcel.java:2920)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6079)
	at android.app.Service.startForeground(Service.java:743)
	at com.doublesymmetry.trackplayer.service.MusicService.startAndStopEmptyNotificationToAvoidANR(MusicService.kt:123)
	at com.doublesymmetry.trackplayer.service.MusicService.onStartCommand(MusicService.kt:96)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4655)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2179) 
	at android.os.Handler.dispatchMessage(Handler.java:106) 
	at android.os.Looper.loopOnce(Looper.java:201) 
	at android.os.Looper.loop(Looper.java:288) 
	at android.app.ActivityThread.main(ActivityThread.java:7918) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

**Comment by brianlenz** [comment]
I can also confirm that the issue still happens in `rc07`. We had tried applying @l3k's [solution](https://github.com/doublesymmetry/react-native-track-player/issues/1986#issuecomment-1579227746) which prevented this error from occurring, but it ended up causing even more problems for us, as Android users reported many issues with playback stability with that patch in place (such as playback events not firing properly and playback randomly stopping).

Even though this error is being reported (for us, in Firebase Crashlytics), I don't have any evidence that indicates the error is affecting end users.

**Comment by Ggayane** [comment]
Is there a way to get rid of "temporary_channel"? on android production right now there are 2 notification categories from on is temporary_channel, and it's not clear what it does.

P.S. I'm not sure if this is a right place to address.
<img width="1043" alt="Screenshot 2023-11-06 at 13 32 17" src="https://github.com/doublesymmetry/react-native-track-player/assets/15812978/185eae0f-436a-4c69-be9d-1910989e5e8a">

![1000000110](https://github.com/doublesymmetry/react-native-track-player/assets/15812978/91d309b7-148c-47ca-bdb7-6ce43c3b639a)

**Comment by nl-danish** [comment]
Is there any new patch available for this issue? And, we're having a bit problem exactly trying to reproduce this on our developer's end, but we're catching this in our Firebase, and it seems like a few of our users have complained for a sudden crash who have Android 14 devices, so we have a hunch about this might be the issue, but we're not able to reproduce it.

If someone can step out the steps on how exactly to reproduce this, we'd be really glad.

**Comment by mcalc001** [comment]
Hey we are also still getting the issue on 4.1.1 - has anyone been able to fix this issue yet?

 "react-native-track-player": "^4.1.1"
 "expo": "~51.0.39",
  "react-native": "0.74.5",

**Comment by devesmee** [comment]
@mcalc001 I ran into the same issue with version 4.1.2 with crashes in Firebase, unable to reproduce locally. Came across a [proposed patch](https://github.com/doublesymmetry/react-native-track-player/issues/2244#issuecomment-2655309493) in another report of the same issue. Maybe you could try this?
