### ISSUE TITLE
App crashing on initialisation of react-native-track-player on RN 0.76.1 and newArchEnabled=true

### ISSUE THREAD

**Issue by varadaraj772** [doublesymmetry/react-native-track-player#2414]
**Description**
**(NOBRIDGE) ERROR Error: Exception in HostObject::get for prop 'TrackPlayerModule': com.facebook.react.internal.turbomodule.core.TurboModuleInteropUtils$ParsingException: Unable to parse @ReactMethod annotation from native module method: TrackPlayerModule.add(). Details: Unable to parse JNI signature. Detected unsupported return class: kotlinx.coroutines.Job**

**Steps To Reproduce**
npm install --save react-native-track-player
npm start

**Code To Reproduce**
import TrackPlayer, { State } from 'react-native-track-player';

**Environment Info:**
 **"react-native-track-player": "^4.1.1",**
 **"@react-native-community/cli": "15.0.0",**
 **"react": "18.3.1",**
 **"react-native": "0.76.1",**

**newArchEnabled=true**
![ss](https://github.com/user-attachments/assets/7a805509-f8bb-49d3-9293-848655f8b947)

**Comment by kapilw360** [comment]
same issue facing

**Comment by saraspaudel** [comment]
@kapilw360 same issue with

    "react-native-track-player": "3.2.0",
        "expo": "52",

**Comment by ega65** [comment]
> downgrade the version to the 3.2.0. and killed the app and rebuild again

Hi ! From where you come with this "solution" ? I have tried it on custom dev mode and got : 

 ERROR  Your app just crashed. See the error below.
java.lang.SecurityException: be.smartconcept.belgahay: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
  android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
  android.os.Parcel.createException(Parcel.java:3041)
  android.os.Parcel.readException(Parcel.java:3024)
  android.os.Parcel.readException(Parcel.java:2966)
  android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6205)
  android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1863)
  android.app.ContextImpl.registerReceiver(ContextImpl.java:1803)
  android.app.ContextImpl.registerReceiver(ContextImpl.java:1791)
  android.content.ContextWrapper.registerReceiver(ContextWrapper.java:766)
  com.google.android.exoplayer2.ui.PlayerNotificationManager.startOrUpdateNotification(PlayerNotificationManager.java:1165)
  com.google.android.exoplayer2.ui.PlayerNotificationManager.handleMessage(PlayerNotificationManager.java:1415)
  com.google.android.exoplayer2.ui.PlayerNotificationManager.$r8$lambda$HT03vPW8fkob-d_ShBn7r7Xo9SA(Unknown Source:0)
  com.google.android.exoplayer2.ui.PlayerNotificationManager$$ExternalSyntheticLambda0.handleMessage(D8$$SyntheticClass:0)
  android.os.Handler.dispatchMessage(Handler.java:102)
  android.os.Looper.loopOnce(Looper.java:222)
  android.os.Looper.loop(Looper.java:314)
  android.app.ActivityThread.main(ActivityThread.java:8716)
  java.lang.reflect.Method.invoke(Native Method)
  com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
  com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
Caused by android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14691)
        at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12225)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3194)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2884)
        at android.os.Binder.execTransactInternal(Binder.java:1346)

**Comment by ayants** [comment]
> downgrade the version to the 3.2.0. and killed the app and rebuild again

I think it is meaningless, downgrading the version will never work, because, this is happening for rn-new-architecture

**Comment by aselcuk** [comment]
I have react-native 0.76.5 version and ı have the same issue, app crashing after installation

<img width="1283" alt="Image" src="https://github.com/user-attachments/assets/abe9cd74-9e4e-4f76-be1e-0c3e9f24c28c" />

**Comment by Pnlvfx** [comment]
Yeah, same error, the library is not working with new architecture.

**Comment by UsmanBaig001** [comment]
it is fixed thank you

**Comment by FaithfulAudio** [comment]
You’ll need to change the code that registers the broadcast receiver in your module’s init() method. Find the following code in your MusicControlModule.java:

IntentFilter filter = new IntentFilter();
filter.addAction(MusicControlNotification.REMOVE_NOTIFICATION);
filter.addAction(MusicControlNotification.MEDIA_BUTTON);
filter.addAction(Intent.ACTION_MEDIA_BUTTON);
filter.addAction(AudioManager.ACTION_AUDIO_BECOMING_NOISY);
receiver = new MusicControlReceiver(this, context);

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
    context.registerReceiver(receiver, filter, Context.RECEIVER_NOT_EXPORTED);
} else {
    context.registerReceiver(receiver, filter);
}

Google introduced new requirements in android 13 and above.

**Comment by Kapil9711** [comment]
i have the same isssue;

**Comment by dhatrishdixit** [comment]
is there any update

**Comment by kapilw360** [comment]
change the library to react-native-sound. It is also has same implementation.

**Comment by jspizziri** [comment]
newArch support has been added here https://github.com/doublesymmetry/react-native-track-player/pull/2478
