### ISSUE TITLE
App crashing on Android

### ISSUE THREAD

**Issue by vbnospace** [doublesymmetry/react-native-track-player#371]
Hi all, I am experiencing a crash thats is happening constantly, and its happening without any prior event. fabric.io is showing these logs 

```
Fatal Exception: com.facebook.react.common.JavascriptException: No task registered for key TrackPlayer, stack:
startHeadlessTask@280:2759
value@17:4857
<unknown>@17:2368
value@17:4111
value@17:2340

       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)
```

I think its related to the issue I opened recently #370 and the way we register event. Please can someone tell me where this bug is coming from ?

**Comment by Guichaguri** [comment]
You have to either `registerBackendService` or `registerEventHandler` right after you register your main component using `AppRegistry.registerComponent`.

**Comment by ntk860** [comment]
@Guichaguri thank you!
