### ISSUE TITLE
[Android] NullPointerException in getPosition

### ISSUE THREAD

**Issue by biomancer** [DoubleSymmetry/react-native-track-player#607]
# Configuration

 React Native Environment Info:
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.58.6 => 0.58.6 

We use fork of react-native-track-player 1.1.3 with minor ios fixes, but they are not related to this android issue. Also I've examined all new commits since 1.1.3 and there are no changes in related part of code, so I think the issue most probably is active for 1.1.4 too

# Issue
I see multiple crashes with

`NullPointerException: Attempt to invoke virtual method 'com.guichaguri.trackplayer.service.player.ExoPlayback com.guichaguri.trackplayer.service.MusicBinder.getPlayback()' on a null object reference`

on Android 7 and 9 in production, could not reproduce it locally. They seem to happen about 1 minute since last app activity, app is probably in background and not playing anything in that moment.

We are using react-native-background-timer to fetch these parameters every 500ms:
```
    TrackPlayer.getPosition()
    TrackPlayer.getBufferedPosition()
    TrackPlayer.getDuration()
    TrackPlayer.getCurrentTrack()
```
We never call TrackPlayer.destroy() in our code.

I'm not familiar with Java, but it seems like there is some race happening between `onServiceDisconnected` in `MusicModule` that nullifies `binder` and `waitForConnection` that should ensure that code is called when `binder` exists. Maybe it's possible to add some kind of mutex or lock to make it thread-safe? Or maybe at least add handling for that exception in methods that use binder, so it won't crash the app?

Here is the report from Android Vitals for Android 9:
```
java.lang.NullPointerException: 
  at com.guichaguri.trackplayer.module.MusicModule.lambda$getPosition$22 (MusicModule.java:406)
  at com.guichaguri.trackplayer.module.-$$Lambda$MusicModule$kz_vCHi_KTfOKaaW0vxI3X8XmdE.run (Unknown Source:4)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:193)
  at android.app.ActivityThread.main (ActivityThread.java:6762)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
```

**Comment by biomancer** [comment]
I've tried to implement fix here https://github.com/perushevandkhmelev-agency/react-native-track-player/commit/20482578aafa0b17e5701d1bcb447e18d79e99e0 , the issue was not reproducible, so I cannot check if that helped until deployed to production, but at least it seems not to break anything. If someone may confirm, that this is sane, I'll create a pr.

**Comment by biomancer** [comment]
I've deployed that potential fix to production, and do not see that particular error for now, but I've found one more crash, that seems to be related and was present in previous version and is happening now too. 

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
    at com.guichaguri.trackplayer.service.MusicBinder.post(MusicBinder.java:22)
    at com.guichaguri.trackplayer.module.MusicModule.waitForConnection(MusicModule.java:100)
    at com.guichaguri.trackplayer.module.MusicModule.getPosition(MusicModule.java:428)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:808)
    at android.os.Handler.dispatchMessage(Handler.java:101)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loop(Looper.java:166)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
    at java.lang.Thread.run(Thread.java:784)
```

**Comment by Guichaguri** [comment]
The first solution looks good, it shouldn't cause problems.

The second error might be related to #473, but I'm not entirely sure. Can you open a new issue to track that?
