### ISSUE TITLE
Error while destroying the track-player

### ISSUE THREAD

**Issue by waheedakhtar694** [DoubleSymmetry/react-native-track-player#788]
While closing the player i am destroying the service but when i call TrackPlayer.destroy() i get this error on android but on IOS it works very good any idea about this ?
and due to this error i can't play any other audio file.
```An error occurred while destroying the service
    java.lang.IllegalArgumentException: Service not registered: com.guichaguri.trackplayer.module.MusicModule@faf8bc9
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1100)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1345)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)
        at com.guichaguri.trackplayer.module.MusicModule.destroy(MusicModule.java:170)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:168)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:818)
11-20 18:46:36.176 28614-29071/com.create.wefiq E/RNTrackPlayer: An error occurred while destroying the service
    java.lang.IllegalArgumentException: Service not registered: com.guichaguri.trackplayer.module.MusicModule@faf8bc9
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1100)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1345)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:616)
        at com.guichaguri.trackplayer.module.MusicModule.destroy(MusicModule.java:170)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallba
ck(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.b```

**Comment by andrewdazs** [comment]
It is happening with me too using `TrackPlayer.destroy()`, just for Android :(
