### ISSUE TITLE
Notification Button Actions causing TrackPlayer crash

### ISSUE THREAD

**Issue by taylormodernized** [DoubleSymmetry/react-native-track-player#812]
#### Configuration
`react-native info`
```
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 5.77 GB / 31.40 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7
```
#### What `react-native-track-player` version are you using?
`1.2.0` from `master`, I've also tried `1.1.8` from NPM

# Issue
I'm getting
```
Service com.guichaguri.trackplayer.service.MusicService has leaked IntentReceiver com.guichaguri.trackplayer.service.MusicManager$1@8941f18 that was originally registered here. Are you missing a call to unregisterReceiver()?
```
in the android logs when triggering remote events from the notification on `RN 0.61.1` and `Android 9 & 10`.
 I'm also using RNN (`react-native-navigation`) 4.0.5.
The `TrackPlayer.getState()` will show the state change to `STATE_STOPPED`, but the audio keeps playing in the background. If I load a new track in, it will play over the original track in the background.

I'm using 

`App.js`
```
Navigation.events().registerAppLaunchedListener(() => {
      TrackPlayer.setupPlayer().then(async ()=>{
            await TrackPlayer.registerPlaybackService(() => require('./service.js'));
            await TrackPlayer.updateOptions({
                    stopWithApp: true,
                    capabilities: [
                      TrackPlayer.CAPABILITY_STOP,
                    ],
            });
      });
});
```

`service.js`
```
import TrackPlayer  from 'react-native-track-player';
module.exports = async ()=>{
    TrackPlayer.addEventListener('remote-stop', () => {
        TrackPlayer.stop();
    });
};

```

**Comment by Guichaguri** [comment]
Does https://github.com/react-native-kit/react-native-track-player/commit/a53707d1c51515347d3db72820f0c20689c3ea26 fixes the issue for you?

**Comment by taylormodernized** [comment]
@Guichaguri It changes the behavior slightly. I'm still getting the previous error message, along with some additional output:
```
12-27 09:07:14.579  2031  2059 V ActivityManager: Attempted to start a foreground service (com.example.app/com.guichaguri.trackplayer.service.MusicService) with a broken notification (no icon: Notification(channel=com.guichaguri.trackplayer pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE))
12-27 09:07:14.581  2341  2341 D RNTrackPlayer: Releasing service resources...
12-27 09:07:14.585  2341  2341 E ActivityThread: Service com.guichaguri.trackplayer.service.MusicService has leaked IntentReceiver com.guichaguri.trackplayer.service.MusicManager$1@3b5788 that was originally registered here. Are you missing a call to unregisterReceiver()?
12-27 09:07:14.585  2341  2341 E ActivityThread: android.app.IntentReceiverLeaked: Service com.guichaguri.trackplayer.service.MusicService has leaked IntentReceiver com.guichaguri.trackplayer.service.MusicManager$1@3b5788 that was originally registered here. Are you missing a call to unregisterReceiver()?
12-27 09:07:14.585  2341  2341 E ActivityThread:        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1588)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:1368)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1515)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1488)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1476)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:627)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.guichaguri.trackplayer.service.MusicManager.onPlay(MusicManager.java:151)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.guichaguri.trackplayer.service.player.ExoPlayback.onPlayerStateChanged(ExoPlayback.java:294)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.guichaguri.trackplayer.service.player.LocalPlayback.onPlayerStateChanged(LocalPlayback.java:192)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$setPlayWhenReady$0(ExoPlayerImpl.java:254)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$OKMPvkXpqXeKaJZFBZ8m9YfNXpE.invokeListener(Unknown Source:4)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:165)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:823)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.google.android.exoplayer2.ExoPlayerImpl.lambda$notifyListeners$6(ExoPlayerImpl.java:716)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$DrcaME6RvvSdC72wmoYPUB4uP5w.run(Unknown Source:4)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:726)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:716)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.google.android.exoplayer2.ExoPlayerImpl.setPlayWhenReady(ExoPlayerImpl.java:254)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.google.android.exoplayer2.SimpleExoPlayer.updatePlayWhenReady(SimpleExoPlayer.java:1224)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.google.android.exoplayer2.SimpleExoPlayer.setPlayWhenReady(SimpleExoPlayer.java:921)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.guichaguri.trackplayer.service.player.ExoPlayback.play(ExoPlayback.java:134)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.guichaguri.trackplayer.service.player.LocalPlayback.play(LocalPlayback.java:150)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.guichaguri.trackplayer.module.MusicModule.lambda$play$10$MusicModule(MusicModule.java:319)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.guichaguri.trackplayer.module.-$$Lambda$MusicModule$6tPjSgn9zq8na8C_MNqG23hrTLw.run(Unknown Source:4)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at android.os.Handler.handleCallback(Handler.java:883)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at android.os.Handler.dispatchMessage(Handler.java:100)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at android.os.Looper.loop(Looper.java:214)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at android.app.ActivityThread.main(ActivityThread.java:7356)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at java.lang.reflect.Method.invoke(Native Method)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
12-27 09:07:14.585  2341  2341 E ActivityThread:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
